// ============================================================
// DADOS DA VIAGEM — Japão Golden Route (24/07 a 08/08/2026)
// Para editar o roteiro, altere este arquivo (ver README.md)
// ============================================================

const TRIP = {
  nome: "Japão — Golden Route",
  subtitulo: "Tóquio · Kyoto · Nara · Hiroshima · Miyajima · Osaka",
  inicio: "2026-07-24",
  fim: "2026-08-08",
  dias: 16,
  noites: 15,
  resumo: "Golden Route clássica em 16 dias, equilibrando cultura tradicional, gastronomia, compras e parques temáticos, com deslocamentos otimizados pela linha Tokaido/Sanyo Shinkansen (Tóquio → Kyoto → Hiroshima → Osaka).",
  bases: [
    { cidade: "Tóquio", noites: 6, periodo: "23–30/07", destaque: "Chegada 23/07 · base fixa no YM Hotel Sugamo · DisneySea, Akihabara, Shibuya, Harajuku, Ginza, Odaiba" },
    { cidade: "Kyoto", noites: 4, periodo: "30/07–03/08", destaque: "Templos, Arashiyama, Gion + bate-volta a Nara" },
    { cidade: "Hiroshima", noites: 1, periodo: "03–04/08", destaque: "Parque da Paz + bate-volta a Miyajima (torii, Monte Misen)" },
    { cidade: "Osaka", noites: 3, periodo: "04–07/08", destaque: "Universal Studios, Dotonbori, Shinsaibashi" },
    { cidade: "Tóquio", noites: 1, periodo: "07–09/08", destaque: "Volta ao YM Sugamo (mala grande esperando) · compras finais e voo de volta" },
  ],
  alertas: [
    "DisneySea e Universal exigem ingresso datado comprado com semanas/meses de antecedência.",
    "JR Pass nacional NÃO compensa neste roteiro — compre trechos avulsos de Shinkansen (app SmartEX).",
    "Crie um Suica na Apple Wallet (Wallet > + > Cartão de Transporte) antes de embarcar.",
    "Malas com L+A+P > 160cm exigem reserva de espaço no Shinkansen — ou use o envio Takkyubin entre hotéis.",
    "Daikoku PA (encontro de carros, sexta à noite) NÃO tem acesso a pé/transporte público — reserve um tour guiado com antecedência (dia 1 ou dia 15).",
    "Habilitação brasileira NÃO vale no Japão (nem com PID) — não dá para alugar carro, dirigir JDM ou pilotar os go-karts de rua. Experiências automotivas: só como passageiro (tours).",
  ],
};

const CIDADES = ["Tóquio", "Kyoto", "Nara", "Hiroshima", "Miyajima", "Osaka"];

const CATS = {
  turismo:     { label: "Pontos turísticos", icon: "⛩️", cor: "#e0344e" },
  restaurante: { label: "Restaurantes",      icon: "🍜", cor: "#f59e0b" },
  cafe:        { label: "Cafés & doces",     icon: "☕", cor: "#8b5a2b" },
  compras:     { label: "Compras",           icon: "🛍️", cor: "#8b5cf6" },
  transporte:  { label: "Transporte",        icon: "🚄", cor: "#0ea5e9" },
  hospedagem:  { label: "Hospedagem",        icon: "🏨", cor: "#10b981" },
  atividade:   { label: "Atividades especiais", icon: "🎢", cor: "#ec4899" },
  conveniencia:{ label: "Konbini & mercados", icon: "🏪", cor: "#14b8a6" },
};

const STATUS = {
  quero:     { label: "Quero ir",   icon: "✅" },
  visitei:   { label: "Já visitei", icon: "🏁" },
  talvez:    { label: "Talvez",     icon: "🤔" },
  pular:     { label: "Pular",      icon: "⏭️" },
  importante:{ label: "Importante", icon: "⭐" },
};

// roteiro: true = faz parte do roteiro oficial | false = sugestão extra
const PLACES = [
  // ================= TÓQUIO — turismo =================
  { id: "sensoji", nome: "Senso-ji", cidade: "Tóquio", cat: "turismo", lat: 35.7148, lng: 139.7967, roteiro: true, dias: [1, 2], rating: 4.7,
    desc: "O templo mais antigo de Tóquio. Chegue antes das 9h para fotos sem multidão; lindo iluminado à noite.", addr: "2-3-1 Asakusa, Taito City", hours: "Templo 6h–17h; área externa 24h", preco: "Grátis" },
  { id: "nakamise", nome: "Nakamise-dori", cidade: "Tóquio", cat: "compras", lat: 35.7118, lng: 139.7965, roteiro: true, dias: [2], rating: 4.5,
    desc: "Rua comercial com +90 lojinhas de artesanato, doces tradicionais e souvenirs, ligando o portão Kaminarimon ao Senso-ji.", addr: "1-36-3 Asakusa, Taito City", hours: "~9h–19h" },
  { id: "ueno", nome: "Parque de Ueno", cidade: "Tóquio", cat: "turismo", lat: 35.7156, lng: 139.7745, roteiro: true, dias: [2], rating: 4.5,
    desc: "Grande parque com museus, templos e lagos. O Museu Nacional de Tóquio fica dentro (~1h30–2h).", addr: "Uenokoen, Taito City", hours: "5h–23h", preco: "Grátis (museus pagos)" },
  { id: "ameyoko", nome: "Ameyoko Market", cidade: "Tóquio", cat: "compras", lat: 35.7096, lng: 139.7743, roteiro: true, dias: [2], rating: 4.3,
    desc: "Mercado de rua animado ao lado de Ueno: comida de rua barata, roupas, cosméticos e doces.", addr: "4 Chome Ueno, Taito City", hours: "~10h–20h" },
  { id: "akihabara", nome: "Akihabara Electric Town", cidade: "Tóquio", cat: "compras", lat: 35.7022, lng: 139.7745, roteiro: true, dias: [2], rating: 4.6,
    desc: "O bairro dos otakus: anime, games, eletrônicos, gachapon e maid cafés. Atenção: Japão usa 100V — confira compatibilidade dos eletrônicos.", addr: "Sotokanda, Chiyoda City", hours: "Lojas ~10h–20h" },
  { id: "yodobashi-akiba", nome: "Yodobashi Camera Akiba", cidade: "Tóquio", cat: "compras", lat: 35.6987, lng: 139.7745, roteiro: true, dias: [2], rating: 4.5,
    desc: "Megastore de eletrônicos com 9 andares: câmeras, games, relógios, eletrodomésticos. Tax-free acima de ¥5.000 (leve o passaporte).", addr: "1-1 Kanda-Hanaokacho, Chiyoda", hours: "9h30–22h" },
  { id: "superpotato", nome: "Super Potato", cidade: "Tóquio", cat: "compras", lat: 35.7008, lng: 139.7716, roteiro: true, dias: [2], rating: 4.4,
    desc: "Lendária loja de games retrô e consoles vintage em Akihabara — Famicom, Game Boy, raridades.", addr: "1-11-2 Sotokanda, Chiyoda", hours: "11h–20h" },
  { id: "mandarake-akiba", nome: "Mandarake Complex", cidade: "Tóquio", cat: "compras", lat: 35.7028, lng: 139.7708, roteiro: true, dias: [2], rating: 4.4,
    desc: "8 andares de mangás raros, figures e colecionáveis usados em ótimo estado. Paraíso do colecionador.", addr: "3-11-12 Sotokanda, Chiyoda", hours: "12h–20h" },
  { id: "shibuya-crossing", nome: "Shibuya Scramble Crossing", cidade: "Tóquio", cat: "turismo", lat: 35.6595, lng: 139.7005, roteiro: true, dias: [3], rating: 4.6,
    desc: "A travessia de pedestres mais movimentada do mundo. Veja também a estátua do Hachiko ao lado.", addr: "Estação Shibuya, saída Hachiko", hours: "24h", preco: "Grátis" },
  { id: "shibuya-sky", nome: "Shibuya Sky", cidade: "Tóquio", cat: "turismo", lat: 35.6585, lng: 139.7022, roteiro: true, dias: [3], rating: 4.7,
    desc: "Mirante a céu aberto no topo do Shibuya Scramble Square — vista 360° de Tóquio. Reserve com antecedência.", addr: "2-24-12 Shibuya", hours: "10h–22h30", preco: "~¥2.500" },
  { id: "takeshita", nome: "Takeshita Street (Harajuku)", cidade: "Tóquio", cat: "compras", lat: 35.6716, lng: 139.7031, roteiro: true, dias: [3], rating: 4.4,
    desc: "A rua da moda jovem e streetwear alternativo, crepes e cafés temáticos. Domingos são bem cheios — vá cedo.", addr: "Jingumae, Shibuya City", hours: "~10h–20h" },
  { id: "catstreet", nome: "Cat Street", cidade: "Tóquio", cat: "compras", lat: 35.6659, lng: 139.7047, roteiro: true, dias: [3], rating: 4.4,
    desc: "Rua entre Harajuku e Shibuya com marcas independentes de streetwear, brechós e cafés descolados.", addr: "Jingumae, Shibuya City", hours: "~11h–20h" },
  { id: "omotesando", nome: "Omotesando", cidade: "Tóquio", cat: "compras", lat: 35.6652, lng: 139.7124, roteiro: true, dias: [3], rating: 4.5,
    desc: "A 'Champs-Élysées' de Tóquio: flagships de grife (Louis Vuitton, Prada, Comme des Garçons) e arquitetura impressionante.", addr: "Omotesando, Shibuya/Minato", hours: "Lojas ~11h–20h" },
  { id: "meijijingu", nome: "Meiji Jingu", cidade: "Tóquio", cat: "turismo", lat: 35.6764, lng: 139.6993, roteiro: false, rating: 4.6,
    desc: "SUGESTÃO EXTRA: santuário xintoísta dentro de uma floresta urbana, colado em Harajuku — encaixa perfeito na manhã do dia 3.", addr: "1-1 Yoyogikamizonocho, Shibuya", hours: "Nascer ao pôr do sol", preco: "Grátis" },
  { id: "disneysea", nome: "Tokyo DisneySea", cidade: "Tóquio", cat: "atividade", lat: 35.6267, lng: 139.885, roteiro: true, dias: [4], rating: 4.8,
    desc: "Parque único no mundo. Destaques: Fantasy Springs (Frozen/Tangled), Mysterious Island, show noturno Believe! Sea of Dreams. Ingresso datado obrigatório (à venda 2 meses antes, ¥8.900–12.900).", addr: "1-13 Maihama, Urayasu", hours: "~9h–21h", preco: "¥8.900–12.900" },
  { id: "shinjukugyoen", nome: "Shinjuku Gyoen", cidade: "Tóquio", cat: "turismo", lat: 35.6852, lng: 139.71, roteiro: true, dias: [5], rating: 4.6, fecha: [1],
    desc: "Um dos jardins mais bonitos de Tóquio — ótimo para relaxar no dia mais leve do roteiro.", addr: "11 Naitomachi, Shinjuku", hours: "9h–17h30 (fecha seg)", preco: "¥500" },
  { id: "biccamera", nome: "Bic Camera Shinjuku", cidade: "Tóquio", cat: "compras", lat: 35.6919, lng: 139.704, roteiro: true, dias: [5], rating: 4.3,
    desc: "Concorrente direto da Yodobashi: eletrônicos, games, relógios e cosméticos com tax-free. Compare preços entre as duas antes de fechar compra grande.", addr: "3-29-1 Shinjuku (saída leste)", hours: "10h–21h" },
  { id: "loft", nome: "Loft Shibuya", cidade: "Tóquio", cat: "compras", lat: 35.6618, lng: 139.6997, roteiro: true, dias: [3], rating: 4.4,
    desc: "7 andares de papelaria de design, presentes criativos, organizadores e itens de casa japoneses — junto com a Tokyu Hands ali perto, paraíso dos presentes inteligentes.", addr: "21-1 Udagawacho, Shibuya", hours: "10h–21h" },
  { id: "bape", nome: "BAPE Store Harajuku (streetwear)", cidade: "Tóquio", cat: "compras", lat: 35.6689,
    lng: 139.7075, roteiro: true, dias: [3], rating: 4.3,
    desc: "A loja da A Bathing Ape — referência do streetwear japonês. Na mesma área: Neighborhood, WTAPS e Undercover (Cat Street/Ura-Harajuku).", addr: "4-21-5 Jingumae, Shibuya", hours: "11h–19h" },
  { id: "pokemon-shibuya", nome: "Pokémon Center Shibuya", cidade: "Tóquio", cat: "compras", lat: 35.662, lng: 139.6987, roteiro: true, dias: [3], rating: 4.5,
    desc: "Dentro do Shibuya Parco (6º andar), com um Mewtwo gigante na entrada — no mesmo andar tem Nintendo Tokyo e Capcom Store!", addr: "Shibuya Parco 6F, 15-1 Udagawacho", hours: "10h–21h" },
  { id: "tocho", nome: "Observatório Metropolitan Gov. Building", cidade: "Tóquio", cat: "turismo", lat: 35.6896, lng: 139.6917, roteiro: true, dias: [5], rating: 4.4,
    desc: "Vista panorâmica GRATUITA do 45º andar — alternativa ao Shibuya Sky. Em dias claros dá para ver o Monte Fuji.", addr: "2-8-1 Nishishinjuku", hours: "9h30–22h", preco: "Grátis" },
  { id: "omoide", nome: "Omoide Yokocho", cidade: "Tóquio", cat: "restaurante", lat: 35.6931, lng: 139.6994, roteiro: true, dias: [5], rating: 4.4,
    desc: "'Beco das Recordações': vielas estreitas com dezenas de izakayas minúsculos de yakitori e lámen. Autêntico e barato.", addr: "1-2 Nishishinjuku", hours: "~17h–24h", preco: "¥1.500–3.000" },
  { id: "kabukicho", nome: "Kabukicho", cidade: "Tóquio", cat: "turismo", lat: 35.6952, lng: 139.7028, roteiro: true, dias: [5], rating: 4.2,
    desc: "O distrito dos letreiros neon (e do Godzilla no prédio Toho). Caminhada noturna clássica; evite insistentes 'promoters'.", addr: "Kabukicho, Shinjuku", hours: "Noite" },
  { id: "ginza", nome: "Ginza (Uniqlo & Muji flagships)", cidade: "Tóquio", cat: "compras", lat: 35.6717, lng: 139.764, roteiro: true, dias: [6], rating: 4.5,
    desc: "Bairro do luxo. Uniqlo de 12 andares e Muji gigante (as maiores do mundo), grifes internacionais e a papelaria Itoya.", addr: "Ginza, Chuo City", hours: "Lojas ~11h–21h" },
  { id: "itoya", nome: "Itoya Ginza", cidade: "Tóquio", cat: "compras", lat: 35.6721, lng: 139.7671, roteiro: true, dias: [6], rating: 4.6,
    desc: "A maior papelaria de Tóquio: 12 andares de canetas, papéis e presentes criativos.", addr: "2-7-15 Ginza", hours: "10h–20h" },
  { id: "tsukiji", nome: "Tsukiji Outer Market", cidade: "Tóquio", cat: "restaurante", lat: 35.6654, lng: 139.7707, roteiro: true, dias: [6], rating: 4.5,
    desc: "Comida de rua e frutos do mar fresquíssimos — melhor no café da manhã/almoço. (O mercado de peixe interno mudou para Toyosu.)", addr: "4 Chome Tsukiji, Chuo", hours: "~5h–14h", preco: "¥1.000–3.000" },
  { id: "teamlab", nome: "teamLab Planets", cidade: "Tóquio", cat: "atividade", lat: 35.6493, lng: 139.7898, roteiro: false, rating: 4.7,
    desc: "SUGESTÃO EXTRA (fora do roteiro atual): arte digital imersiva onde você anda na água. Se mudar de ideia, exige ingresso com horário marcado (esgota rápido). Fica em Toyosu, ao lado do A PIT.", addr: "6-1-16 Toyosu, Koto", hours: "9h–22h", preco: "~¥3.800" },
  { id: "divercity", nome: "Odaiba / DiverCity (Gundam)", cidade: "Tóquio", cat: "turismo", lat: 35.6251, lng: 139.7754, roteiro: true, dias: [6], rating: 4.4,
    desc: "Ilha artificial: estátua do Gundam em tamanho real, réplica da Estátua da Liberdade e vista do Rainbow Bridge à noite. Vá pelo trem panorâmico Yurikamome.", addr: "1-1-10 Aomi, Koto", hours: "Shopping 11h–21h" },
  { id: "tokyostation", nome: "Tokyo Station / Character Street", cidade: "Tóquio", cat: "compras", lat: 35.6812, lng: 139.7671, roteiro: true, dias: [7, 15], rating: 4.5,
    desc: "Área comercial subterrânea com lojas oficiais de Ghibli, Pokémon, Hello Kitty e mais — perfeita para compras de última hora.", addr: "1-9-1 Marunouchi, Chiyoda", hours: "10h–20h30" },
  { id: "pokemon-mega", nome: "Pokémon Center Mega Tokyo", cidade: "Tóquio", cat: "compras", lat: 35.7292, lng: 139.7191, roteiro: true, dias: [7], rating: 4.6,
    desc: "No Sunshine City (Ikebukuro), uma das maiores lojas Pokémon do Japão. Ao lado da Animate principal.", addr: "Sunshine City 2F, Ikebukuro", hours: "10h–20h" },
  { id: "animate-ikebukuro", nome: "Animate Ikebukuro", cidade: "Tóquio", cat: "compras", lat: 35.7295, lng: 139.7175, roteiro: true, dias: [7], rating: 4.5,
    desc: "Loja principal da Animate — 9 andares de mercadoria oficial de anime, a maior do Japão.", addr: "1-20-7 Higashiikebukuro", hours: "11h–21h" },
  { id: "sanrio", nome: "Sanrio Puroland", cidade: "Tóquio", cat: "atividade", lat: 35.6252, lng: 139.4291, roteiro: true, dias: [1], rating: 4.4,
    desc: "Parque indoor da Hello Kitty e amigos em Tama (~45 min de Shinjuku pela linha Keio): shows, atrações, comida temática e MUITA loja. Ingresso com data e horário marcado — compre online antes. Por ser coberto, funciona em qualquer clima.", addr: "1-31 Ochiai, Tama", hours: "~9h30–17h (varia por dia)", preco: "~¥3.900–4.900" },
  { id: "tokyotower", nome: "Tokyo Tower", cidade: "Tóquio", cat: "turismo", lat: 35.6586, lng: 139.7454, roteiro: true, dias: [1], rating: 4.5,
    desc: "A torre vermelha símbolo de Tóquio (333m). Deck principal a 150m; lindíssima iluminada à noite. Ao lado fica o templo Zojo-ji, com a foto clássica da torre atrás do templo.", addr: "4-2-8 Shibakoen, Minato", hours: "9h–22h30", preco: "¥1.500 (deck principal)" },
  { id: "zojoji", nome: "Zojo-ji", cidade: "Tóquio", cat: "turismo", lat: 35.6575, lng: 139.7482, roteiro: true, dias: [1], rating: 4.4,
    desc: "Templo histórico dos xoguns Tokugawa, aos pés da Tokyo Tower — o contraste templo + torre é uma das fotos mais icônicas da cidade. Grátis.", addr: "4-7-35 Shibakoen, Minato", hours: "6h–17h30", preco: "Grátis" },
  { id: "nakano", nome: "Nakano Broadway", cidade: "Tóquio", cat: "compras", lat: 35.7089, lng: 139.6654, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o shopping cult dos colecionadores — dezenas de lojas Mandarake (a original!), figures raras, mangás vintage e relógios. Menos turístico que Akihabara. 5 min de trem de Shinjuku.", addr: "5-52-15 Nakano", hours: "12h–20h (varia por loja)" },
  { id: "shimokitazawa", nome: "Shimokitazawa", cidade: "Tóquio", cat: "compras", lat: 35.6613, lng: 139.6681, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o bairro indie de Tóquio — brechós incríveis, discos de vinil, cafés e teatros. Perfeito para moda vintage a bom preço.", addr: "Kitazawa, Setagaya", hours: "Lojas ~12h–20h" },
  { id: "ghibli", nome: "Museu Ghibli (Mitaka)", cidade: "Tóquio", cat: "atividade", lat: 35.6962, lng: 139.5704, roteiro: false, rating: 4.6, fecha: [2],
    desc: "SUGESTÃO EXTRA: o museu do Studio Ghibli (Totoro, A Viagem de Chihiro). RESERVA OBRIGATÓRIA e concorrida: ingressos vendem no dia 10 do mês anterior, no site oficial. Ótimo plano B de chuva.", addr: "1-1-83 Shimorenjaku, Mitaka", hours: "10h–18h (fecha ter)", preco: "¥1.000" },
  { id: "yanaka", nome: "Yanaka Ginza", cidade: "Tóquio", cat: "turismo", lat: 35.7276, lng: 139.7669, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: a Tóquio antiga que sobreviveu — rua comercial retrô com lanches baratos e gatos. Combina com Ueno (fica ao lado, dia 2).", addr: "3-13-1 Yanaka, Taito", hours: "~10h–18h" },
  { id: "imperial", nome: "Jardins do Palácio Imperial", cidade: "Tóquio", cat: "turismo", lat: 35.6852, lng: 139.7528, roteiro: false, rating: 4.4, fecha: [1, 5],
    desc: "SUGESTÃO EXTRA: os East Gardens do Palácio Imperial, com ruínas do Castelo de Edo — grátis e a 10 min a pé da Tokyo Station. ATENÇÃO: fecha às segundas e sextas.", addr: "1-1 Chiyoda", hours: "9h–17h (fecha seg e sex)", preco: "Grátis" },
  { id: "skytree", nome: "Tokyo Skytree", cidade: "Tóquio", cat: "turismo", lat: 35.7101, lng: 139.8107, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: torre de 634m perto de Asakusa — combine com o dia 2 se quiser vista do alto.", addr: "1-1-2 Oshiage, Sumida", hours: "10h–21h", preco: "¥2.100–3.400" },
  { id: "shibuya109", nome: "Shibuya 109", cidade: "Tóquio", cat: "compras", lat: 35.6597, lng: 139.6987, roteiro: true, dias: [3], rating: 4.3,
    desc: "Templo da moda jovem japonesa — dezenas de marcas em um só prédio icônico.", addr: "2-29-1 Dogenzaka, Shibuya", hours: "10h–21h" },
  { id: "donki-shinjuku", nome: "Don Quijote Shinjuku", cidade: "Tóquio", cat: "compras", lat: 35.6946, lng: 139.7036, roteiro: true, dias: [5], rating: 4.3,
    desc: "Loja de departamento caótica e maravilhosa: cosméticos, doces, eletrônicos, souvenirs bizarros. Tax-free. Aberta até tarde.", addr: "1-16-5 Kabukicho", hours: "24h" },
  { id: "cosme", nome: "@cosme Tokyo (Harajuku)", cidade: "Tóquio", cat: "compras", lat: 35.6706, lng: 139.7026, roteiro: true, dias: [3], rating: 4.4,
    desc: "Curadoria dos cosméticos japoneses mais bem avaliados — ótimo para testar antes de comprar.", addr: "1-14-27 Jingumae", hours: "11h–21h" },
  // Tóquio/Yokohama — cultura automotiva
  { id: "daikoku", nome: "Daikoku PA — encontro de carros JDM", cidade: "Tóquio", cat: "atividade", lat: 35.4599, lng: 139.6807, roteiro: true, dias: [1, 15], rating: 4.7,
    desc: "O encontro de carros mais famoso do mundo, numa área de descanso da via expressa na baía de Yokohama: Skylines, RX-7, Supras, kaido racers, supercarros. Sexta e sábado à noite — carros chegam ~21h–22h, pico 23h–1h. ATENÇÃO: só é acessível DE CARRO (sem trem, ônibus ou pedestres); para turista, o caminho é tour guiado saindo de Tóquio (~¥15.000–25.000/pessoa, com busca no hotel — alguns levam você num R34/RX-7/Supra). Táxi custa ¥8.000–15.000 por trecho e é difícil conseguir a volta. A polícia às vezes fecha o PA quando lota — tours têm pontos alternativos. As duas sextas possíveis: dia 1 (24/07) ou dia 15 (07/08).", addr: "Daikokufuto 15, Tsurumi, Yokohama", hours: "PA 24h; encontros sex/sáb ~21h–2h", preco: "Tour ~¥15.000–25.000" },
  { id: "tatsumi-pa", nome: "Tatsumi PA — encontro de carros (Wangan)", cidade: "Tóquio", cat: "atividade", lat: 35.6444, lng: 139.8129, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: o 'irmão menor' do Daikoku na via expressa Shuto, com vista do skyline de Tóquio — encontros menores e mais locais, madrugada de sexta para sábado. Também SÓ acessível de carro; muitos tours de Daikoku incluem parada aqui na mesma noite.", addr: "Tatsumi, Koto City", hours: "Noites de sex/sáb" },
  { id: "nissan-crossing", nome: "Nissan Crossing (Ginza)", cidade: "Tóquio", cat: "atividade", lat: 35.6709, lng: 139.7637, roteiro: true, dias: [6], rating: 4.4,
    desc: "Showroom-galeria da Nissan no cruzamento principal de Ginza: GT-R, protótipos e clássicos em exposições rotativas, com café que desenha o carro que você escolher na espuma do latte. GRÁTIS — parada rápida (~30–45 min) que encaixa na manhã de Ginza.", addr: "Ginza Place, 5-8-1 Ginza, Chuo", hours: "10h–20h", preco: "Grátis" },
  { id: "apit", nome: "A PIT Autobacs Shinonome (peças & JDM)", cidade: "Tóquio", cat: "compras", lat: 35.6472, lng: 139.804, roteiro: true, dias: [6], rating: 4.4,
    desc: "A 'meca' das lojas de carro do Japão: megastore da Autobacs com peças de tuning, rodas, miniaturas, roupas e café automotivo — e carros interessantes estacionando o tempo todo. Fica em Shinonome/Toyosu: encaixa na passagem por Odaiba no dia 6.", addr: "2-7-20 Shinonome, Koto", hours: "9h–21h", preco: "Grátis (entrada)" },
  { id: "nismo-showroom", nome: "NISMO Showroom (Omori Factory)", cidade: "Tóquio", cat: "atividade", lat: 35.4776, lng: 139.686, roteiro: false, rating: 4.5, fecha: [1, 2, 3, 4, 5],
    desc: "SUGESTÃO EXTRA: o quartel-general da NISMO em Yokohama — showroom GRÁTIS com carros de corrida históricos, GT-Rs e loja de peças/souvenirs oficiais. SÓ ABRE FIM DE SEMANA (10h–17h): na viagem, cabe no sáb (dia 2) ou dom (dia 3) — ~45 min de trem de Tóquio (estação Tsurumi + ônibus). Confirme o calendário no site antes.", addr: "6-1 Daikokucho, Tsurumi, Yokohama", hours: "Sáb/dom 10h–17h", preco: "Grátis" },
  { id: "nissan-hq", nome: "Nissan Global HQ Gallery (Yokohama)", cidade: "Tóquio", cat: "atividade", lat: 35.4646, lng: 139.6247, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: galeria GRATUITA na sede mundial da Nissan, colada na estação Yokohama (~30 min de Tóquio): novos modelos, carros históricos e de corrida, boutique com itens NISMO e café. Pode entrar nos carros! Combina com o NISMO Showroom num 'desvio Yokohama' de meio dia.", addr: "1-1-1 Takashima, Nishi-ku, Yokohama", hours: "10h–20h", preco: "Grátis" },
  // Tóquio — restaurantes/cafés
  { id: "ichiran", nome: "Ichiran Shibuya", cidade: "Tóquio", cat: "restaurante", lat: 35.6614, lng: 139.7009, roteiro: true, dias: [3], rating: 4.5,
    desc: "O famoso ramen tonkotsu em cabines individuais — peça pelo ticket na máquina.", addr: "1-22-7 Jinnan, Shibuya", hours: "24h", preco: "~¥1.500" },
  { id: "uobei", nome: "Uobei Shibuya", cidade: "Tóquio", cat: "restaurante", lat: 35.6605, lng: 139.6983, roteiro: true, dias: [3], rating: 4.3,
    desc: "Sushi em esteira de alta velocidade, pedido por tablet — divertido e barato.", addr: "2-29-11 Dogenzaka", hours: "11h–23h", preco: "¥110–150/prato" },
  { id: "gonpachi", nome: "Gonpachi Nishi-Azabu", cidade: "Tóquio", cat: "restaurante", lat: 35.6604, lng: 139.7241, roteiro: true, rating: 4.3,
    desc: "O izakaya que inspirou a cena do filme Kill Bill — jantar temático e animado.", addr: "1-13-11 Nishiazabu, Minato", hours: "11h30–23h30", preco: "¥3.000–5.000" },
  { id: "afuri", nome: "Afuri Ramen (Harajuku)", cidade: "Tóquio", cat: "restaurante", lat: 35.6684, lng: 139.7104, roteiro: true, rating: 4.4,
    desc: "Ramen leve à base de yuzu (cítrico) — contraponto refrescante ao tonkotsu pesado.", addr: "3-63-1 Sendagaya (e outras unidades)", hours: "11h–23h", preco: "~¥1.400" },
  { id: "rokurinsha", nome: "Rokurinsha (Tokyo Ramen Street)", cidade: "Tóquio", cat: "restaurante", lat: 35.6797, lng: 139.7687, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o tsukemen (macarrão para mergulhar no caldo) mais famoso de Tóquio, na Ramen Street do subsolo da Tokyo Station — perfeito para o jantar do dia 15.", addr: "Tokyo Station B1, First Avenue", hours: "7h30–23h", preco: "~¥1.200" },
  { id: "gyukatsu", nome: "Gyukatsu Motomura (Shibuya)", cidade: "Tóquio", cat: "restaurante", lat: 35.658, lng: 139.6994, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: bife empanado frito por fora e cru por dentro, que você termina de grelhar na pedra quente individual — febre entre visitantes, espere fila.", addr: "3-18-10 Shibuya", hours: "11h–22h", preco: "~¥1.800" },
  { id: "pokemoncafe", nome: "Pokémon Café", cidade: "Tóquio", cat: "cafe", lat: 35.6839, lng: 139.7742, roteiro: true, rating: 4.5,
    desc: "Café oficial Pokémon em Nihonbashi. RESERVA OBRIGATÓRIA pelo site oficial, abre vagas com semanas de antecedência.", addr: "Nihonbashi Takashimaya S.C. East 5F", hours: "10h30–22h", preco: "¥2.000–3.500" },
  { id: "gundamcafe", nome: "Base de fãs Gundam (Akihabara)", cidade: "Tóquio", cat: "cafe", lat: 35.6986, lng: 139.7714, roteiro: false, rating: 4.2,
    desc: "SUGESTÃO: região de Akihabara tem cafés e lojas temáticas de mecha/Gundam — confirme unidades abertas na data.", addr: "Sotokanda, Chiyoda", hours: "Varia" },
  { id: "hoshino", nome: "Hoshino Coffee (Shinjuku)", cidade: "Tóquio", cat: "cafe", lat: 35.6917, lng: 139.7036, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: kissaten moderno com café de sifão e panquecas soufflé — café da manhã japonês clássico.", addr: "Várias unidades", hours: "9h–22h", preco: "~¥1.000" },
  { id: "kirbycafe", nome: "Kirby Café Tokyo", cidade: "Tóquio", cat: "cafe", lat: 35.71, lng: 139.8107, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: café permanente do Kirby no Tokyo Solamachi (4º andar, base da Skytree — combina com Asakusa no dia 2). Pratos temáticos fofíssimos. RESERVA obrigatória: abre dia 10 de cada mês (18h JST) e esgota em segundos.", addr: "Tokyo Solamachi 4F, Oshiage", hours: "10h–20h30", preco: "¥2.000–3.500" },
  { id: "animaxcafe", nome: "Animax Café+ (colabs Persona & anime)", cidade: "Tóquio", cat: "cafe", lat: 35.6706, lng: 139.704, roteiro: false, rating: 4.2,
    desc: "SUGESTÃO EXTRA: café de colaborações temáticas rotativas em Harajuku (já teve Persona 5, e vários animes/jogos). O tema muda a cada temporada — confira o que está em cartaz na data e se precisa de reserva. Encaixa no dia 3 (Harajuku).", addr: "Jingumae 1-15-2, 3F, Shibuya", hours: "~11h–21h", preco: "¥2.000–3.500" },
  { id: "goldengai", nome: "Shinjuku Golden Gai", cidade: "Tóquio", cat: "restaurante", lat: 35.6939, lng: 139.7047, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: labirinto de ~200 bares minúsculos (2–8 lugares cada) em vielas retrô de Shinjuku — atmosfera única. Encaixa na noite do dia 5. Atenção: alguns cobram 'table charge'; procure os bares com placa 'tourists welcome'.", addr: "1-1-6 Kabukicho, Shinjuku", hours: "~19h–1h", preco: "Couvert ~¥500–1.000 + bebidas" },
  { id: "shirohige", nome: "Shirohige's Cream Puff (Totoro)", cidade: "Tóquio", cat: "cafe", lat: 35.66, lng: 139.656, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: os famosos choux (bombas de creme) em formato do Totoro, aprovados pelo Studio Ghibli. Fica perto de Shimokitazawa/Setagaya — combina com o passeio ao bairro indie.", addr: "5-3-1 Daita, Setagaya", hours: "10h30–19h (fecha ter)", preco: "~¥600" },
  // Tóquio — transporte/hospedagem
  { id: "narita", nome: "Aeroporto de Narita (NRT)", cidade: "Tóquio", cat: "transporte", lat: 35.7719, lng: 140.3929, roteiro: true, dias: [16],
    desc: "Narita Express (~60–90 min) ou Keisei Skyliner (~40 min até Ueno). Chegue 3h antes de voos internacionais." },
  { id: "haneda", nome: "Aeroporto de Haneda (HND)", cidade: "Tóquio", cat: "transporte", lat: 35.5494, lng: 139.7798, roteiro: true, dias: [16],
    desc: "Tokyo Monorail ou trem Keikyu (~30–40 min até o centro)." },
  { id: "shinjuku-sta", nome: "Estação Shinjuku", cidade: "Tóquio", cat: "transporte", lat: 35.6896, lng: 139.7006, roteiro: true,
    desc: "A estação mais movimentada do mundo. Hub das linhas Yamanote, Chuo, Marunouchi e Ōedo." },
  { id: "maihama", nome: "Estação Maihama (Disney)", cidade: "Tóquio", cat: "transporte", lat: 35.6363, lng: 139.8804, roteiro: true, dias: [4],
    desc: "JR Keiyo Line desde Tokyo Station (~15–20 min) + Disney Resort Line até o DisneySea." },
  { id: "hotel-tokyo", nome: "Hotel: YM Hotel Sugamo", cidade: "Tóquio", cat: "hospedagem", lat: 35.744, lng: 139.7402, roteiro: true, addr: "5-38-11 Sugamo (YM Building), Toshima-ku 170-0002",
    desc: "SUA BASE EM TÓQUIO — reserva de 23/07 a 09/08 (fica reservado a viagem TODA). Check-in 16h / check-out 11h. Quarto triplo. Bairro tranquilo em Sugamo 5-chome (não é colado na estação JR). ESTAÇÕES MAIS PRÓXIMAS: bonde Toden Arakawa (Tokyo Sakura Tram) — Nishigahara-yonchome ~8 min a pé e Shin-Koshinzuka ~13 min; metrô Toei Mita (Nishi-sugamo) ~13 min; JR Yamanote (Sugamo) ~15 min a pé — de Sugamo, Ikebukuro fica a 2 estações. COM MALA vale táxi de Ikebukuro/Sugamo (~¥1.000). DICA DE OURO: o quarto fica reservado o tempo todo — DEIXE a mala grande aqui durante o Kansai (dias 7–15) e viaje só com mochila. A rua Jizo-dori ('Harajuku das vovós') e vários konbini ficam no caminho até a estação." },
  // Tóquio — konbini, mercados e conveniência perto do hotel (Sugamo)
  { id: "sugamo-jizo", nome: "Jizo-dori (rua comercial de Sugamo)", cidade: "Tóquio", cat: "compras", lat: 35.7345, lng: 139.7385, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: a rua comercial tradicional coladinha no hotel — o 'Harajuku das vovós'. Lojinhas, doces (o famoso shio daifuku), comidinhas baratas e mercado de bairro. Ótima para o primeiro jantar e para sentir o Japão do dia a dia.", addr: "Sugamo, Toshima-ku", hours: "~10h–18h (lojas)" },
  { id: "konbini-sugamo", nome: "Konbini 24h (perto do hotel)", cidade: "Tóquio", cat: "conveniencia", lat: 35.7437, lng: 139.7405, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: lojas de conveniência 24h (7-Eleven, FamilyMart, Lawson) nas ruas ao redor do hotel (Sugamo 5-chome) e no caminho pela Jizo-dori até a estação. Comida pronta boa e barata, ATM internacional, água, guarda-chuva, carregar o Suica — resolve quase tudo.", addr: "Sugamo 5-chome, Toshima-ku", hours: "24h" },
  { id: "super-sugamo", nome: "Supermercado (Sugamo)", cidade: "Tóquio", cat: "conveniencia", lat: 35.734, lng: 139.7405, roteiro: false, rating: 4.2,
    desc: "SUGESTÃO EXTRA: supermercados de bairro perto da estação de Sugamo (busque 'supermarket' no mapa) — frutas, bentôs com desconto no fim do dia, bebidas e lanches bem mais baratos que no konbini. Bom para abastecer o quarto.", addr: "Sugamo, Toshima-ku", hours: "~10h–22h" },
  { id: "donki-ikebukuro", nome: "MEGA Don Quijote Ikebukuro", cidade: "Tóquio", cat: "conveniencia", lat: 35.7295, lng: 139.716, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: megaloja 24h (cosméticos, doces, souvenirs, eletrônicos) a 1 estação/2 min de trem de Sugamo, em Ikebukuro. Tax-free — perfeita para compras de qualquer hora.", addr: "Ikebukuro (saída leste), Toshima", hours: "24h" },

  // ================= KYOTO =================
  { id: "fushimi", nome: "Fushimi Inari Taisha", cidade: "Kyoto", cat: "turismo", lat: 34.9671, lng: 135.7727, roteiro: true, dias: [8], rating: 4.8,
    desc: "O santuário dos mil torii vermelhos. VÁ ANTES DAS 8h! Suba até o mirante Yotsutsuji (~1h ida e volta). Aberto 24h e gratuito.", addr: "68 Fukakusa Yabunouchicho, Fushimi", hours: "24h", preco: "Grátis" },
  { id: "kiyomizu", nome: "Kiyomizu-dera", cidade: "Kyoto", cat: "turismo", lat: 34.9949, lng: 135.785, roteiro: true, dias: [8], rating: 4.7,
    desc: "Templo histórico com deck de madeira e vista da cidade. Desça pelas ruelas de Sannenzaka e Ninenzaka.", addr: "1-294 Kiyomizu, Higashiyama", hours: "6h–18h", preco: "¥400" },
  { id: "sannenzaka", nome: "Sannenzaka & Ninenzaka", cidade: "Kyoto", cat: "compras", lat: 34.9966, lng: 135.781, roteiro: true, dias: [8], rating: 4.6,
    desc: "Ruelas históricas preservadas com lojinhas tradicionais, doces e cafés — o caminho perfeito descendo do Kiyomizu-dera.", addr: "Higashiyama", hours: "Lojas ~10h–18h" },
  { id: "gion", nome: "Gion (Hanamikoji-dori)", cidade: "Kyoto", cat: "turismo", lat: 35.0037, lng: 135.7752, roteiro: true, dias: [7, 8], rating: 4.6,
    desc: "Bairro histórico das gueixas. Caminhe ao entardecer — chance de avistar maiko. NUNCA persiga ou fotografe de perto (há multas).", addr: "Gion, Higashiyama", hours: "Sempre aberto", preco: "Grátis" },
  { id: "bamboo", nome: "Arashiyama Bamboo Grove", cidade: "Kyoto", cat: "turismo", lat: 35.017, lng: 135.671, roteiro: true, dias: [9], rating: 4.6,
    desc: "O bosque de bambu — vá ao amanhecer (antes das 8h), lota a partir das 9h. Combine com o templo Tenryu-ji ao lado.", addr: "Sagaogurayama, Ukyo", hours: "24h", preco: "Grátis" },
  { id: "tenryuji", nome: "Tenryu-ji", cidade: "Kyoto", cat: "turismo", lat: 35.0158, lng: 135.6737, roteiro: true, dias: [9], rating: 4.6,
    desc: "Patrimônio UNESCO com um dos jardins zen mais bonitos do Japão, colado no bosque de bambu.", addr: "68 Susukinobabacho, Ukyo", hours: "8h30–17h", preco: "¥500" },
  { id: "togetsukyo", nome: "Ponte Togetsukyo", cidade: "Kyoto", cat: "turismo", lat: 35.0126, lng: 135.6776, roteiro: true, dias: [9], rating: 4.5,
    desc: "Ponte cênica sobre o rio Hozu. Opcionais: barco no rio, Sagano Scenic Railway (trenzinho romântico) e Parque dos Macacos de Iwatayama.", addr: "Arashiyama", hours: "24h", preco: "Grátis" },
  { id: "monkeypark", nome: "Parque dos Macacos Iwatayama", cidade: "Kyoto", cat: "atividade", lat: 35.0093, lng: 135.6772, roteiro: false, rating: 4.4,
    desc: "OPCIONAL: subida de ~20 min até macacos soltos e vista panorâmica de Kyoto.", addr: "Arashiyama", hours: "9h–16h", preco: "¥800" },
  { id: "sagano", nome: "Sagano Romantic Train", cidade: "Kyoto", cat: "atividade", lat: 35.0186, lng: 135.6813, roteiro: true, dias: [9], rating: 4.5, fecha: [3],
    desc: "O 'trenzinho romântico': trem retrô aberto que percorre 7km do desfiladeiro do rio Hozu (~25 min). Reserve assento com antecedência (site JR West ou estação); o vagão 5 é totalmente aberto. Costuma não operar às quartas.", addr: "Estação Torokko Saga (ao lado da JR Saga-Arashiyama)", hours: "9h–16h (varia)", preco: "¥880" },
  { id: "katsukura", nome: "Katsukura (tonkatsu)", cidade: "Kyoto", cat: "restaurante", lat: 34.9855, lng: 135.758, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: tonkatsu famoso no The Cube (11º andar da Kyoto Station) — você mesmo mói o gergelim do molho. Ótima alternativa à Ramen Street no dia 9.", addr: "Kyoto Station, The Cube 11F", hours: "11h–22h", preco: "~¥1.800" },
  { id: "kyotostation", nome: "Kyoto Station / Isetan / Porta", cidade: "Kyoto", cat: "compras", lat: 34.9858, lng: 135.7585, roteiro: true, dias: [9], rating: 4.5,
    desc: "A estação é uma atração em si. Compras na Isetan e no shopping subterrâneo Porta; artesanato, matcha e doces yatsuhashi.", addr: "Higashishiokoji, Shimogyo", hours: "10h–20h" },
  { id: "ramenstreet", nome: "Kyoto Ramen Street", cidade: "Kyoto", cat: "restaurante", lat: 34.9857, lng: 135.7587, roteiro: true, dias: [9], rating: 4.4,
    desc: "10 famosas casas de ramen de todo o Japão reunidas no 10º andar da Kyoto Station.", addr: "Kyoto Station 10F", hours: "11h–22h", preco: "~¥1.200" },
  { id: "nishiki", nome: "Nishiki Market", cidade: "Kyoto", cat: "restaurante", lat: 35.005, lng: 135.7649, roteiro: true, dias: [10], rating: 4.4,
    desc: "'A cozinha de Kyoto': rua coberta de ~400m com dezenas de barracas — tofu yuba, matcha, facas artesanais, espetinhos.", addr: "Nishikikoji-dori", hours: "~10h–18h", preco: "¥500–2.000" },
  { id: "yoshimura", nome: "Arashiyama Yoshimura", cidade: "Kyoto", cat: "restaurante", lat: 35.0132, lng: 135.6779, roteiro: true, dias: [9], rating: 4.4,
    desc: "Soba artesanal com vista para o rio e a ponte Togetsukyo — almoço perfeito em Arashiyama.", addr: "3 Sagatenryuji Susukinobabacho", hours: "11h–17h", preco: "~¥1.500" },
  { id: "kaiseki", nome: "Kaiseki em Gion (ex: Gion Karyo)", cidade: "Kyoto", cat: "restaurante", lat: 35.0031, lng: 135.7746, roteiro: true, rating: 4.6,
    desc: "A alta gastronomia tradicional de Kyoto em vários pratos. Reserve com 1–4 semanas de antecedência (muitos exigem reserva via hotel).", addr: "Gion", hours: "Jantar 17h–22h", preco: "¥8.000–20.000" },
  { id: "menbaka", nome: "Menbaka Fire Ramen", cidade: "Kyoto", cat: "restaurante", lat: 35.023, lng: 135.753, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o 'ramen de fogo' — o chef joga óleo em brasa sobre a tigela e labaredas sobem quase ao teto (espetáculo garantido). Perto do Castelo Nijo. Chegue cedo/reserve; siga as instruções de segurança (mãos na mesa!).", addr: "757 Minamiitto, Nakagyo", hours: "11h30–14h30, 17h–20h (fecha dom)", preco: "~¥1.500" },
  { id: "arabica", nome: "% Arabica Arashiyama", cidade: "Kyoto", cat: "cafe", lat: 35.0136, lng: 135.6772, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: um dos cafés mais famosos do Japão, com vista para o rio — perfeito após o bosque de bambu.", addr: "3-47 Sagatenryuji", hours: "9h–18h", preco: "~¥600" },
  { id: "kinkakuji", nome: "Kinkaku-ji (Pavilhão Dourado)", cidade: "Kyoto", cat: "turismo", lat: 35.0394, lng: 135.7292, roteiro: false, rating: 4.7,
    desc: "SUGESTÃO EXTRA: o templo dourado à beira do lago — encaixa na tarde do dia 9 (30 min de ônibus de Arashiyama).", addr: "1 Kinkakujicho, Kita", hours: "9h–17h", preco: "¥500" },
  { id: "nintendomuseum", nome: "Nintendo Museum", cidade: "Kyoto", cat: "atividade", lat: 34.9046, lng: 135.7995, roteiro: false, rating: 4.7,
    desc: "SUGESTÃO EXTRA para gamers: museu oficial da Nintendo em Uji (20 min de trem de Kyoto). Ingresso por SORTEIO com ~3 meses de antecedência no site oficial.", addr: "56 Ogura Kaguraden, Uji", hours: "10h–18h", preco: "~¥3.300" },
  { id: "ginkakuji", nome: "Ginkaku-ji + Caminho do Filósofo", cidade: "Kyoto", cat: "turismo", lat: 35.027, lng: 135.7982, roteiro: false, rating: 4.6,
    desc: "SUGESTÃO EXTRA: o Pavilhão Prateado, com jardim zen de areia, e o Caminho do Filósofo — passeio à beira do canal ligando a Ginkaku-ji até perto de Gion.", addr: "2 Ginkakujicho, Sakyo", hours: "8h30–17h", preco: "¥500" },
  { id: "nijo", nome: "Castelo Nijo", cidade: "Kyoto", cat: "turismo", lat: 35.0142, lng: 135.7481, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: castelo dos xoguns (UNESCO) com os 'pisos rouxinol' que cantam ao pisar — anti-ninja! Bom plano B de chuva parcial.", addr: "541 Nijojocho, Nakagyo", hours: "8h45–17h", preco: "¥1.300" },
  { id: "yasaka", nome: "Santuário Yasaka & Parque Maruyama", cidade: "Kyoto", cat: "turismo", lat: 35.0037, lng: 135.7787, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: santuário na entrada de Gion, aberto e iluminado à noite (lanternas lindas) — encaixe natural na noite do dia 8. Grátis.", addr: "625 Gionmachi Kitagawa", hours: "24h", preco: "Grátis" },
  { id: "hotel-kyoto", nome: "Hotel: Rest Collection Gion-Shijo", cidade: "Kyoto", cat: "hospedagem", lat: 35.0031, lng: 135.769, roteiro: true, addr: "Kawaramachi-dori Shijo-sagaru, Inaricho 335 (Ed. Hōgen), Shimogyo-ku",
    desc: "4 noites (30/07–03/08). Check-in 15h / check-out 10h. Localização excelente, em Kawaramachi/Shijo — coração de Kyoto, com Gion e Nishiki Market a 5–10 min a pé. COMO CHEGAR ÀS ESTAÇÕES: Hankyu Kyoto-Kawaramachi ~3 min a pé (linha p/ Arashiyama via Katsura e p/ Osaka); Keihan Gion-Shijo ~6 min (atravessando o rio — linha direta p/ Fushimi Inari no dia 8); ponto de ônibus Shijo-Kawaramachi na porta (hub das linhas municipais). Para a Kyoto Station (Shinkansen, dias 10/11): ônibus 4/17/205 (~15–20 min) ou táxi (~10 min)." },
  { id: "konbini-kyoto", nome: "Konbini 24h (Kawaramachi)", cidade: "Kyoto", cat: "conveniencia", lat: 35.0033, lng: 135.769, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: 7-Eleven, FamilyMart e Lawson por toda a Kawaramachi/Shijo, a 1–3 min do hotel. Comida pronta, ATM internacional, água e o que precisar, 24h.", addr: "Kawaramachi/Shijo, Shimogyo-ku", hours: "24h" },
  { id: "donki-kyoto", nome: "Don Quijote Shijo Kawaramachi", cidade: "Kyoto", cat: "conveniencia", lat: 35.0058, lng: 135.7683, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: o Don Quijote a ~3 min a pé do hotel, subindo a Kawaramachi-dori — de tudo (cosméticos, doces, souvenirs, eletrônicos), tax-free, aberto até 1h da manhã.", addr: "321 Shioyacho, Kawaramachi-dori, Nakagyo", hours: "10h–1h" },

  // ================= NARA =================
  { id: "narapark", nome: "Parque de Nara (veados)", cidade: "Nara", cat: "turismo", lat: 34.6851, lng: 135.843, roteiro: true, dias: [10], rating: 4.7,
    desc: "+1.200 veados sagrados soltos que 'reverenciam' por biscoitos shika senbei (~¥200). Cuidado: alguns são insistentes!", addr: "Nara Park", hours: "24h", preco: "Grátis" },
  { id: "todaiji", nome: "Todai-ji (Grande Buda)", cidade: "Nara", cat: "turismo", lat: 34.689, lng: 135.8398, roteiro: true, dias: [10], rating: 4.8,
    desc: "Abriga o Daibutsu, uma das maiores estátuas de bronze do mundo (15m) — impressionante de perto.", addr: "406-1 Zoshicho, Nara", hours: "7h30–17h30", preco: "¥800" },
  { id: "kasuga", nome: "Kasuga Taisha", cidade: "Nara", cat: "turismo", lat: 34.6812, lng: 135.8484, roteiro: true, dias: [10], rating: 4.6,
    desc: "Santuário xintoísta cercado por milhares de lanternas de pedra na floresta.", addr: "160 Kasuganocho, Nara", hours: "6h30–17h30", preco: "Pátio grátis; interior ¥700" },
  { id: "nakatanidou", nome: "Nakatanidou (mochi)", cidade: "Nara", cat: "cafe", lat: 34.6817, lng: 135.8272, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: o famoso mochi socado em alta velocidade — show à parte e mochi fresquinho (~¥200).", addr: "29 Hashimotocho, Nara", hours: "10h–19h", preco: "¥200" },
  { id: "kintetsu-nara", nome: "Estação Kintetsu Nara", cidade: "Nara", cat: "transporte", lat: 34.6845, lng: 135.8281, roteiro: true, dias: [10],
    desc: "De Kyoto: JR Nara Line (~45 min) ou Kintetsu (mais central). Bate-volta de meio dia é suficiente." },

  // ================= HIROSHIMA =================
  { id: "peacepark", nome: "Parque Memorial da Paz", cidade: "Hiroshima", cat: "turismo", lat: 34.3927, lng: 132.4525, roteiro: true, dias: [11], rating: 4.8,
    desc: "Visita emocionalmente intensa e importante, com o Genbaku Dome (Cúpula da Bomba Atômica). Reserve 2–3h com o museu.", addr: "1-1 Nakajimacho, Naka", hours: "Parque 24h", preco: "Grátis" },
  { id: "peacemuseum", nome: "Museu Memorial da Paz", cidade: "Hiroshima", cat: "turismo", lat: 34.3917, lng: 132.453, roteiro: true, dias: [11], rating: 4.8,
    desc: "O museu sobre o bombardeio de 1945 — essencial, forte e educativo.", addr: "1-2 Nakajimacho, Naka", hours: "8h30–19h (verão)", preco: "¥200" },
  { id: "okonomimura", nome: "Okonomimura", cidade: "Hiroshima", cat: "restaurante", lat: 34.3907, lng: 132.462, roteiro: true, dias: [11], rating: 4.4,
    desc: "Prédio inteiro dedicado ao okonomiyaki estilo Hiroshima (com lámen na massa!) — dezenas de bancas.", addr: "5-13 Shintenchi, Naka", hours: "11h–22h", preco: "~¥1.200" },
  { id: "hiroshimacastle", nome: "Castelo de Hiroshima", cidade: "Hiroshima", cat: "turismo", lat: 34.4027, lng: 132.4595, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: reconstrução do castelo 'Carpa' com museu e vista do topo — 15 min a pé do Peace Park, se sobrar tempo antes do ferry.", addr: "21-1 Motomachi, Naka", hours: "9h–18h", preco: "¥370" },
  { id: "hiroshima-sta", nome: "Estação Hiroshima", cidade: "Hiroshima", cat: "transporte", lat: 34.3978, lng: 132.4754, roteiro: true, dias: [11, 12],
    desc: "Shinkansen Sanyo de/para Kyoto (~1h40) e Shin-Osaka (~1h20–1h40). Trem local JR Sanyo até Miyajimaguchi (~25–30 min). Coin lockers grandes para guardar a mala no bate-volta a Miyajima (dia 12)." },
  { id: "hotel-hiroshima", nome: "Hotel: Room in Naka-ku (Airbnb)", cidade: "Hiroshima", cat: "hospedagem", lat: 34.393, lng: 132.452, roteiro: true, dias: [11], addr: "2-5-12 Tōkaichimachi, Naka-ku",
    desc: "1 noite (03–04/08). Check-in 15h / check-out 10h. Fica em Naka-ku, praticamente COLADO no Parque Memorial da Paz (~10 min a pé) — perfeito para o dia 11. COMO CHEGAR ÀS ESTAÇÕES: bonde Hiroden 'Tōkaichi-machi' a ~5 min a pé (linhas para a Hiroshima Station e sentido Miyajimaguchi). Para a Hiroshima Station (Shinkansen): bonde ~15–20 min ou táxi ~10 min. Para Miyajima (dia 12): bonde/JR até Miyajimaguchi + ferry." },
  { id: "konbini-hiroshima", nome: "Konbini 24h (perto do Peace Park)", cidade: "Hiroshima", cat: "conveniencia", lat: 34.3928, lng: 132.4525, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: lojas de conveniência 24h (7-Eleven, Lawson, FamilyMart) a poucos minutos do hotel e do Peace Park. Bom para o café da manhã antes de sair cedo para Miyajima no dia 12.", addr: "Naka-ku (perto de Tōkaichimachi)", hours: "24h" },
  { id: "donki-hiroshima", nome: "Don Quijote Hiroshima Hacchobori", cidade: "Hiroshima", cat: "conveniencia", lat: 34.3905, lng: 132.4622, roteiro: false, rating: 4.3,
    desc: "SUGESTÃO EXTRA: o Don Quijote de 5 andares no centro comercial (Hondori/Shintenchi), ~10–12 min a pé do hotel — de tudo, tax-free. Combina com a rua coberta Hondori e o Okonomimura.", addr: "5-3 Shintenchi, Naka-ku", hours: "~10h–madrugada" },

  // ================= MIYAJIMA =================
  { id: "itsukushima", nome: "Santuário Itsukushima & Torii Flutuante", cidade: "Miyajima", cat: "turismo", lat: 34.296, lng: 132.3198, roteiro: true, dias: [12], rating: 4.8,
    desc: "Um dos cartões-postais do Japão. Maré alta = torii 'flutuando'; maré baixa = dá para caminhar até ele. Confira a tábua de marés! Iluminado à noite.", addr: "1-1 Miyajimacho, Hatsukaichi", hours: "6h30–18h", preco: "¥300" },
  { id: "misen", nome: "Monte Misen (Ropeway)", cidade: "Miyajima", cat: "atividade", lat: 34.2926, lng: 132.3237, roteiro: true, dias: [12], rating: 4.6,
    desc: "Teleférico + caminhada até o topo: vista panorâmica da Baía de Hiroshima. Alternativa: trilha (~1h30–2h subida).", addr: "Momijidani Park", hours: "9h–16h30", preco: "~¥2.000 ida e volta" },
  { id: "miyajima-omotesando", nome: "Omotesando (rua comercial de Miyajima)", cidade: "Miyajima", cat: "compras", lat: 34.3005, lng: 132.3218, roteiro: true, dias: [12], rating: 4.4,
    desc: "Rua principal da ilha: momiji manju (doce símbolo local), anago-meshi (enguia sobre arroz), shamoji (espátulas de arroz), laca e madeira.", addr: "Miyajimacho", hours: "~9h30–18h" },
  { id: "anagomeshi", nome: "Anagomeshi Ueno", cidade: "Miyajima", cat: "restaurante", lat: 34.3122, lng: 132.302, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: a casa centenária (1901) do anago-meshi — enguia-do-mar grelhada sobre arroz, a especialidade de Miyajima. Fica ao lado da estação Miyajimaguchi; perfeita no almoço do dia 12 antes do trem. O bentō para viagem é lendário.", addr: "1-5-11 Miyajimaguchi, Hatsukaichi", hours: "10h–19h", preco: "~¥2.700" },
  { id: "miyajimaguchi", nome: "Ferry Miyajimaguchi ⇄ Miyajima", cidade: "Miyajima", cat: "transporte", lat: 34.3126, lng: 132.303, roteiro: true, dias: [12],
    desc: "Ferry JR ou Matsudai (~10 min). Última travessia costuma ser ~22h — confirme no dia." },

  // ================= OSAKA =================
  { id: "usj", nome: "Universal Studios Japan", cidade: "Osaka", cat: "atividade", lat: 34.6654, lng: 135.4323, roteiro: true, dias: [13], rating: 4.7,
    desc: "Super Nintendo World (+ Donkey Kong Country, novo em 2026!), Harry Potter, Jurassic Park, Minion Park. 25º aniversário = lotado: Express Pass praticamente essencial. Chegue 30–45 min antes da abertura.", addr: "2-1-33 Sakurajima, Konohana", hours: "~8h30–21h", preco: "¥8.600–11.400 + Express Pass ¥7.000–13.000" },
  { id: "dotonbori", nome: "Dotonbori (Glico Sign)", cidade: "Osaka", cat: "turismo", lat: 34.6687, lng: 135.5013, roteiro: true, dias: [12, 14], rating: 4.6,
    desc: "O coração pulsante de Osaka: letreiros neon (Glico Man, caranguejo gigante), canal, takoyaki e okonomiyaki. Imperdível à noite.", addr: "Dotonbori, Chuo", hours: "24h (melhor à noite)", preco: "Grátis" },
  { id: "osakacastle", nome: "Castelo de Osaka", cidade: "Osaka", cat: "turismo", lat: 34.6873, lng: 135.5262, roteiro: true, dias: [14], rating: 4.6,
    desc: "Exterior e jardins gratuitos e muito fotogênicos; museu interno opcional (~1h).", addr: "1-1 Osakajo, Chuo", hours: "9h–17h", preco: "Parque grátis; museu ¥600" },
  { id: "shinsaibashi", nome: "Shinsaibashi-suji", cidade: "Osaka", cat: "compras", lat: 34.6726, lng: 135.5011, roteiro: true, dias: [14], rating: 4.5,
    desc: "A principal rua de compras coberta de Osaka: moda, streetwear e o Don Quijote gigante (Ebisu Tower, com roda-gigante!).", addr: "Shinsaibashisuji, Chuo", hours: "Lojas ~11h–21h" },
  { id: "dendentown", nome: "Den Den Town", cidade: "Osaka", cat: "compras", lat: 34.658, lng: 135.5062, roteiro: true, dias: [14], rating: 4.4,
    desc: "O 'Akihabara de Osaka' (Nipponbashi): eletrônicos, games, anime — com Mandarake, Animate e lojas retrô.", addr: "Nipponbashi, Naniwa", hours: "~10h–20h" },
  { id: "kuromon", nome: "Kuromon Ichiba Market", cidade: "Osaka", cat: "restaurante", lat: 34.6654, lng: 135.5062, roteiro: true, dias: [15], rating: 4.4,
    desc: "'A cozinha de Osaka': wagyu grelhado na hora, ouriço fresco, frutas premium — vá com fome.", addr: "2-4-1 Nipponbashi", hours: "~9h–18h", preco: "¥1.000–4.000" },
  { id: "hozenji", nome: "Hozenji Yokocho", cidade: "Osaka", cat: "turismo", lat: 34.6673, lng: 135.503, roteiro: true, dias: [14], rating: 4.5,
    desc: "Vielas de pedra tradicionais atrás de Dotonbori, com o templo coberto de musgo — contraste perfeito com o neon.", addr: "1 Chome Namba, Chuo", hours: "24h", preco: "Grátis" },
  { id: "kanidoraku", nome: "Kani Doraku Dotonbori", cidade: "Osaka", cat: "restaurante", lat: 34.669, lng: 135.501, roteiro: true, dias: [12, 14], rating: 4.3,
    desc: "O icônico restaurante de caranguejo com o letreiro gigante mecânico.", addr: "1-6-18 Dotonbori", hours: "11h–22h", preco: "¥4.000–10.000" },
  { id: "wanaka", nome: "Takoyaki Wanaka", cidade: "Osaka", cat: "restaurante", lat: 34.6659, lng: 135.5027, roteiro: true, dias: [12], rating: 4.4,
    desc: "Um dos takoyaki mais famosos de Osaka — bolinhos de polvo na chapa.", addr: "11-19 Namba Sennichimae", hours: "10h–21h", preco: "~¥600 (8 un.)" },
  { id: "daruma", nome: "Daruma Kushikatsu (Dotonbori)", cidade: "Osaka", cat: "restaurante", lat: 34.6686, lng: 135.5019, roteiro: true, dias: [14], rating: 4.3,
    desc: "Espetinhos empanados e fritos, especialidade de Osaka. Regra sagrada: NÃO molhe o espetinho duas vezes no molho comum.", addr: "1-6-4 Dotonbori", hours: "11h–22h30", preco: "~¥2.000" },
  { id: "horai551", nome: "551 Horai (butaman)", cidade: "Osaka", cat: "restaurante", lat: 34.666, lng: 135.501, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: a instituição de Osaka do butaman (pão de porco no vapor) — fila constante, mas anda rápido; ótimo lanche de rua barato. Várias unidades (Namba, Dotonbori, estações). Prove também o shumai.", addr: "3-6-3 Namba, Chuo (e outras)", hours: "10h–22h", preco: "~¥210/un." },
  { id: "rikuro", nome: "Rikuro's Cheesecake (Namba)", cidade: "Osaka", cat: "cafe", lat: 34.6642, lng: 135.5025, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: o lendário cheesecake 'pulante' (jiggly) assado na hora, com o carimbo do galo no topo — sai quentinho e tremendo do forno. Um clássico barato de Osaka (Namba). Espere fila que anda rápido.", addr: "3-2-28 Namba, Chuo", hours: "9h–21h30", preco: "~¥965 (inteiro)" },
  { id: "mizuno", nome: "Okonomiyaki Mizuno", cidade: "Osaka", cat: "restaurante", lat: 34.6685, lng: 135.5023, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: okonomiyaki premiado em Dotonbori desde 1945 — espere fila, vale a pena.", addr: "1-4-15 Dotonbori", hours: "11h–21h", preco: "~¥1.500" },
  { id: "umeda", nome: "Umeda — Grand Front & Hankyu", cidade: "Osaka", cat: "compras", lat: 34.7043, lng: 135.4959, roteiro: true, dias: [15], rating: 4.4,
    desc: "O polo de compras 'chique' de Osaka, junto à Estação Osaka: Grand Front (design e gastronomia), Hankyu (grife e depachika incrível no subsolo) e Daimaru (Pokémon Center + Nintendo Osaka no 13º andar). Alternativa de compras finais no dia 15.", addr: "Umeda, Kita", hours: "10h–20h" },
  { id: "pokemon-osaka", nome: "Pokémon Center Osaka", cidade: "Osaka", cat: "compras", lat: 34.7017, lng: 135.4983, roteiro: true, rating: 4.5,
    desc: "No Daimaru Umeda (13º andar) — junto com um Nintendo Osaka na mesma loja!", addr: "Daimaru Umeda 13F", hours: "10h–20h" },
  { id: "umeda-sky", nome: "Umeda Sky Building", cidade: "Osaka", cat: "turismo", lat: 34.7053, lng: 135.4903, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: observatório flutuante com vista 360° — ótimo plano B de chuva junto com os shoppings de Umeda.", addr: "1-1-88 Oyodonaka, Kita", hours: "9h30–22h30", preco: "¥2.000" },
  { id: "shinsekai", nome: "Shinsekai & Tsutenkaku", cidade: "Osaka", cat: "turismo", lat: 34.6525, lng: 135.5063, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: bairro retrô com a torre Tsutenkaku e os kushikatsu originais — Osaka 'raiz'.", addr: "Ebisuhigashi, Naniwa", hours: "24h", preco: "Grátis" },
  { id: "glion", nome: "GLION Museum (carros clássicos)", cidade: "Osaka", cat: "atividade", lat: 34.6563, lng: 135.4303, roteiro: false, rating: 4.4, fecha: [1],
    desc: "SUGESTÃO EXTRA: museu de ~80 carros clássicos raros em armazéns históricos de tijolo vermelho no porto de Osaka (Tempozan, ao lado do aquário Kaiyukan). Clima 'vintage romance' + café/steakhouse no complexo. Fecha às segundas.", addr: "2-6-39 Kaigandori, Minato", hours: "11h–17h (fecha seg)", preco: "¥1.300" },
  { id: "kaiyukan", nome: "Aquário Kaiyukan", cidade: "Osaka", cat: "atividade", lat: 34.6545, lng: 135.429, roteiro: false, rating: 4.6,
    desc: "SUGESTÃO EXTRA: um dos maiores aquários do mundo, com tubarões-baleia num tanque gigante de 9m de profundidade. Fica na baía, perto da USJ — plano B de chuva excelente.", addr: "1-1-10 Kaigandori, Minato", hours: "10h–20h", preco: "¥2.700" },
  { id: "harukas", nome: "Abeno Harukas 300", cidade: "Osaka", cat: "turismo", lat: 34.6462, lng: 135.5133, roteiro: false, rating: 4.5,
    desc: "SUGESTÃO EXTRA: observatório no topo de um dos prédios mais altos do Japão (300m) — vista 360° de Osaka, incrível ao pôr do sol.", addr: "1-1-43 Abenosuji, Abeno", hours: "9h–22h", preco: "¥2.000" },
  { id: "nambayasaka", nome: "Namba Yasaka Jinja", cidade: "Osaka", cat: "turismo", lat: 34.6633, lng: 135.4948, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o santuário com a cabeça de leão gigante (12m) que 'engole os maus espíritos' — foto única, 10 min a pé de Namba. Grátis.", addr: "2-9-19 Motomachi, Naniwa", hours: "6h30–17h", preco: "Grátis" },
  { id: "shinosaka", nome: "Estação Shin-Osaka", cidade: "Osaka", cat: "transporte", lat: 34.7335, lng: 135.5002, roteiro: true, dias: [12, 15],
    desc: "Estação do Shinkansen de Osaka. Metrô Midosuji liga a Umeda/Namba em ~15 min." },
  { id: "universalcity", nome: "Estação Universal City", cidade: "Osaka", cat: "transporte", lat: 34.6672, lng: 135.4363, roteiro: true, dias: [13],
    desc: "JR Loop Line até Nishikujo + JR Yumesaki Line (~20–30 min do centro)." },
  { id: "namba-sta", nome: "Estação Namba", cidade: "Osaka", cat: "transporte", lat: 34.6666, lng: 135.5, roteiro: true,
    desc: "Hub de Namba: metrô Midosuji, Kintetsu e acesso a pé a Dotonbori." },
  { id: "hotel-osaka", nome: "Hotel: BLUE Shimanouchi (Airbnb)", cidade: "Osaka", cat: "hospedagem", lat: 34.6706, lng: 135.5028, roteiro: true, addr: "2-2-16 Shimanouchi, Chuo-ku",
    desc: "3 noites (04–07/08). Check-in 16h / check-out 10h (self check-in). Em Shimanouchi, a ~5 min a pé de Dotonbori. COMO CHEGAR ÀS ESTAÇÕES: Metrô Nagahoribashi (linhas Sakaisuji/Nagahori) ~5 min a pé; Namba (Midosuji/Yotsubashi/Sennichimae + Nankai/Kintetsu) ~8 min; Shinsaibashi (Midosuji) ~8 min. Para Shin-Osaka (Shinkansen, dia 15): Midosuji direto de Namba/Shinsaibashi (~12–15 min). Para a Universal (dia 13): ver o transporte do dia." },
  { id: "konbini-osaka", nome: "Konbini 24h (Namba/Shimanouchi)", cidade: "Osaka", cat: "conveniencia", lat: 34.6708, lng: 135.5025, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: konbini 24h (7-Eleven, FamilyMart, Lawson) por toda a região de Shimanouchi/Namba, a 1–3 min do hotel. Comida pronta, ATM internacional, água e essenciais a qualquer hora.", addr: "Shimanouchi, Chuo-ku", hours: "24h" },
  { id: "donki-osaka", nome: "Don Quijote Dotonbori (roda-gigante)", cidade: "Osaka", cat: "conveniencia", lat: 34.6688, lng: 135.5017, roteiro: false, rating: 4.4,
    desc: "SUGESTÃO EXTRA: o icônico Don Quijote 24h à beira do canal de Dotonbori, com a roda-gigante Ebisu Tower na fachada — ~5 min a pé do hotel. De tudo, tax-free, e um marco para fotos à noite.", addr: "7-13 Soemoncho, Chuo-ku", hours: "24h" },
];

// ================= ROTEIRO DIA A DIA =================
const DAYS = [
  { d: 0, date: "2026-07-23", dow: "qui", cidade: "Tóquio", titulo: "Chegada ao Japão · Haneda → Sugamo", prioridade: "Chegada", leve: true,
    periodos: [
      { t: "Desembarque (Haneda)", desc: "Imigração + alfândega em Haneda (HND). ANTES de sair do aeroporto: ative/carregue o Suica no Apple Wallet (ou compre um Welcome Suica) e pegue o eSIM/Pocket WiFi. Água no konbini, banheiro e respira — bem-vindo ao Japão! 🎌" },
      { t: "Aeroporto → Hotel (Sugamo)", desc: "MAIS CONFORTÁVEL COM MALA: Airport Limousine Bus até Ikebukuro (~¥1.400, ~50 min) + táxi (~10 min, ~¥1.200) direto ao hotel. DE TREM (~50 min, ~¥560): Keikyu Airport Line até Shinagawa → JR Yamanote (sentido Ikebukuro) até Sugamo; do JR Sugamo são ~15 min a pé até o hotel (ou táxi ~¥1.000). ATENÇÃO: o hotel NÃO fica colado na estação — fica em Sugamo 5-chome, ~15 min a pé da JR Sugamo (ou perto do bonde Toden em Nishigahara-yonchome). Guarde o endereço offline: 5-38-11 Sugamo." },
      { t: "Check-in 16h+ / Noite", desc: "Check-in no YM Hotel Sugamo (a partir das 16h — chegou antes? deixe as malas na recepção). Jantar leve: konbini 24h, a rua Jizo-dori ao lado ou Ikebukuro (2 min de trem). Durma cedo para vencer o jet lag — amanhã é o dia 1 (Puroland)!" },
    ],
    transporte: "Com mala (recomendado): Airport Limousine Bus até Ikebukuro + táxi ao hotel. De trem: Haneda → Keikyu/Shinagawa → JR Yamanote até Sugamo + ~15 min a pé (ou táxi)",
    obs: "Voo longo — priorize dormir bem esta noite. Tenha ienes em espécie e o endereço do hotel salvo offline (5-38-11 Sugamo). Cada um do trio precisa do próprio Suica.",
    places: ["haneda", "sugamo-jizo", "konbini-sugamo", "super-sugamo", "hotel-tokyo"] },
  { d: 1, date: "2026-07-24", dow: "sex", cidade: "Tóquio", titulo: "Sanrio Puroland e Tokyo Tower", prioridade: "Muito recomendado",
    periodos: [
      { t: "Manhã (9h30–14h)", desc: "Sanrio Puroland em Tama (~45 min de Shinjuku pela linha Keio até Keio-Tama-Center): shows da Hello Kitty e amigos, atrações indoor, comida temática e compras. Ingresso com horário marcado — compre online antes." },
      { t: "Tarde (15h30–18h)", desc: "De volta ao centro: Tokyo Tower e o templo Zojo-ji ao lado — a foto clássica do templo com a torre atrás. Suba ao deck principal (150m) no fim da tarde." },
      { t: "Noite (18h–21h)", desc: "Torre iluminada + jantar na região (Azabudai/Roppongi) ou perto do hotel. Alternativa tranquila: Senso-ji iluminado em Asakusa, como aquecimento para o dia 2." },
      { t: "Madrugada (opcional, 22h–2h)", desc: "SEXTA À NOITE = Daikoku PA, o encontro de carros mais famoso do mundo (Yokohama). Só de tour guiado com busca no hotel (~¥15.000–25.000) — reserve com antecedência. Se o jet lag pesar, a outra sexta é o dia 15 (07/08)." },
    ],
    transporte: "Keio Line: Shinjuku → Keio-Tama-Center (~40 min); volta + metrô Ōedo até Akabanebashi (Tokyo Tower)",
    obs: "Você chega em 23/07 e dorme no YM Sugamo, então acorda descansado para este primeiro dia. Puroland é todo coberto (ótimo para qualquer clima) e menos cheio em dia de semana — confirme o horário no site oficial e compre o ingresso datado. Daikoku: escolha entre esta sexta e a do dia 15 — reserve o tour da que escolher.",
    places: ["sanrio", "tokyotower", "zojoji", "sensoji", "daikoku", "hotel-tokyo"] },
  { d: 2, date: "2026-07-25", dow: "sáb", cidade: "Tóquio", titulo: "Asakusa, Ueno e Akihabara", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (9h–12h)", desc: "Senso-ji cedo (antes das 9h) + Nakamise-dori: 90 lojinhas de artesanato e doces. ~2h." },
      { t: "Tarde (13h–16h)", desc: "Ueno (10 min de trem): parque, opcional Museu Nacional, e o mercado Ameyoko para comida de rua e compras baratas." },
      { t: "Noite (16h–21h)", desc: "Akihabara: Yodobashi (eletrônicos), Mandarake (colecionáveis), Super Potato (retrô games), Animate e gachapon." },
    ],
    transporte: "Metrô — linhas Ginza/Hibiya",
    obs: "Compre/ative o Suica logo no 1º uso. Eletrônicos: Japão usa 100V — verifique compatibilidade.",
    places: ["sensoji", "nakamise", "ueno", "ameyoko", "akihabara", "yodobashi-akiba", "superpotato", "mandarake-akiba", "skytree", "yanaka"] },
  { d: 3, date: "2026-07-26", dow: "dom", cidade: "Tóquio", titulo: "Shibuya, Harajuku e Omotesando", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (9h–12h)", desc: "Shibuya Scramble Crossing + estátua do Hachiko. Suba ao Shibuya Sky (reserve antes) — 1h–1h30." },
      { t: "Tarde (12h–16h)", desc: "Harajuku: Takeshita Street (moda jovem, crepes), Cat Street (marcas independentes) e @cosme (cosméticos)." },
      { t: "Noite (16h–20h)", desc: "Omotesando: flagships de grife e Omotesando Hills. Jantar: Ichiran (ramen) ou Uobei (sushi de esteira)." },
    ],
    transporte: "Metrô — linha Yamanote",
    obs: "Domingo = Takeshita Street mais cheia; vá logo após o almoço. Extra que encaixa de manhã: santuário Meiji Jingu.",
    places: ["shibuya-crossing", "shibuya-sky", "takeshita", "catstreet", "omotesando", "shibuya109", "cosme", "loft", "bape", "pokemon-shibuya", "ichiran", "uobei", "gyukatsu", "meijijingu"] },
  { d: 4, date: "2026-07-27", dow: "seg", cidade: "Tóquio", titulo: "Tokyo DisneySea — dia inteiro", prioridade: "Imperdível",
    periodos: [
      { t: "Dia inteiro", desc: "Foque uma área por vez: Fantasy Springs (Frozen/Tangled), Mysterious Island (Journey to the Center of the Earth), Mediterranean Harbor. Use o app oficial para filas e reservas." },
      { t: "Noite", desc: "Fique para o show noturno Believe! Sea of Dreams (água, luz e fogos) antes de voltar." },
    ],
    transporte: "Do hotel (Sugamo): JR Yamanote até Tokyo Station (~18 min) → JR Keiyo Line até Maihama (~15 min) → Disney Resort Line (monotrilho) até a DisneySea. Saia cedo para chegar antes da abertura",
    obs: "Ingresso datado OBRIGATÓRIO (venda 2 meses antes, ¥8.900–12.900). Considere Premier Access para pular filas. Compras: Duffy & Friends, itens do 25º aniversário.",
    places: ["disneysea", "maihama"] },
  { d: 5, date: "2026-07-28", dow: "ter", cidade: "Tóquio", titulo: "Shinjuku (dia mais leve)", prioridade: "Muito recomendado", leve: true,
    periodos: [
      { t: "Manhã (9h–11h)", desc: "Shinjuku Gyoen (jardim, ¥500) ou observatório do Metropolitan Government Building (GRÁTIS, vista do Fuji em dias claros)." },
      { t: "Tarde (12h–17h)", desc: "Compras: Don Quijote (de tudo!), Yodobashi/Bic Camera (eletrônicos), Isetan (grife), Lumine (moda jovem)." },
      { t: "Noite (18h–21h)", desc: "Omoide Yokocho: jantar autêntico de yakitori/lámen em vielas. Depois, neon de Kabukicho." },
    ],
    transporte: "Metrô — linhas Marunouchi/Ōedo",
    obs: "Dia planejado para descansar as pernas antes de Kyoto.",
    places: ["shinjukugyoen", "tocho", "donki-shinjuku", "biccamera", "omoide", "kabukicho", "hoshino"] },
  { d: 6, date: "2026-07-29", dow: "qua", cidade: "Tóquio", titulo: "Tsukiji, Ginza e Odaiba", prioridade: "Muito recomendado",
    periodos: [
      { t: "Manhã (8h–11h)", desc: "Tsukiji Outer Market CEDO: frutos do mar fresquíssimos no café da manhã (várias barracas fecham ~14h, por isso comece por aqui)." },
      { t: "Meio-dia (11h–15h)", desc: "Ginza: flagships Uniqlo (12 andares) e Muji, grifes e a papelaria Itoya. Parada rápida no Nissan Crossing (showroom grátis com GT-R e clássicos, no cruzamento principal)." },
      { t: "Tarde/Noite (15h–20h)", desc: "Odaiba pelo trem panorâmico Yurikamome: Gundam do DiverCity e vista noturna do Rainbow Bridge. Para o fã de carros: a megaloja A PIT Autobacs Shinonome fica em Toyosu, no caminho." },
    ],
    transporte: "Metrô + Yurikamome (Odaiba)",
    obs: "Ordem pensada para o calor e os horários: mercado cedo, Ginza no ar-condicionado no auge do sol, Odaiba ao entardecer.",
    places: ["tsukiji", "ginza", "itoya", "nissan-crossing", "apit", "divercity"] },
  { d: 7, date: "2026-07-30", dow: "qui", cidade: "Tóquio → Kyoto", titulo: "Shinkansen para Kyoto", prioridade: "Imperdível (transição)",
    periodos: [
      { t: "Manhã", desc: "Livre em Tóquio: Ikebukuro (Pokémon Center Mega + Animate), Nakano Broadway (colecionáveis) ou compras finais." },
      { t: "Tarde", desc: "Shinkansen Tokaido Tóquio → Kyoto (Nozomi ~2h15). Compre assento reservado pelo app SmartEX." },
      { t: "Noite", desc: "Check-in no Rest Collection Gion-Shijo e caminhada por Gion ao entardecer (a ~10 min a pé do hotel) — as ruas de madeira iluminadas são lindas." },
    ],
    transporte: "Shinkansen Tokaido (Tóquio/Shinagawa → Kyoto). Do hotel de Kyoto: metrô/ônibus até Kawaramachi, ou táxi (~10 min da Kyoto Station)",
    obs: "Como o YM Sugamo fica reservado a viagem toda, DEIXE a mala grande lá e faça todo o Kansai (dias 7–15) só com uma mochila/bagagem de mão — mais prático e barato que Takkyubin.",
    places: ["pokemon-mega", "animate-ikebukuro", "nakano", "tokyostation", "gion", "hotel-kyoto"] },
  { d: 8, date: "2026-07-31", dow: "sex", cidade: "Kyoto", titulo: "Fushimi Inari, Kiyomizu-dera e Gion", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (7h–10h)", desc: "Fushimi Inari Taisha — os mil torii. VÁ O MAIS CEDO POSSÍVEL (7h). Suba até o Yotsutsuji (~1h ida e volta). Grátis." },
      { t: "Tarde (11h–16h)", desc: "Kiyomizu-dera (deck de madeira com vista) e descida pelas ruelas históricas de Sannenzaka/Ninenzaka." },
      { t: "Noite (17h–21h)", desc: "Gion: Hanamikoji-dori ao entardecer, possível avistar maiko. Jantar tradicional na área (kaiseki se reservou)." },
    ],
    transporte: "Trem JR Nara Line (Fushimi) + ônibus municipal + caminhada",
    obs: "Fushimi Inari e Kiyomizu-dera são os locais mais fotografados do Japão — horário é tudo. Nunca fotografe gueixas de perto.",
    places: ["fushimi", "kiyomizu", "sannenzaka", "gion", "yasaka", "kaiseki"] },
  { d: 9, date: "2026-08-01", dow: "sáb", cidade: "Kyoto", titulo: "Arashiyama e Kyoto Station", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (7h–10h)", desc: "Bosque de Bambu ao amanhecer (antes das 8h!) + Templo Tenryu-ji (jardim UNESCO)." },
      { t: "Tarde (10h30–14h)", desc: "Ponte Togetsukyo, opcional barco no rio Hozu, Sagano Romantic Train ou Parque dos Macacos. Almoço: soba no Yoshimura com vista do rio." },
      { t: "Tarde/Noite (15h–20h)", desc: "Kyoto Station: arquitetura, compras (Isetan/Porta: matcha, yatsuhashi, facas) e jantar na Kyoto Ramen Street." },
    ],
    transporte: "Trem JR San-in ou ônibus até Arashiyama",
    obs: "Bosque lota após 9h. Extra que encaixa à tarde: Kinkaku-ji (Pavilhão Dourado, 30 min de ônibus).",
    places: ["bamboo", "tenryuji", "togetsukyo", "sagano", "monkeypark", "yoshimura", "arabica", "kyotostation", "ramenstreet", "katsukura", "kinkakuji"] },
  { d: 10, date: "2026-08-02", dow: "dom", cidade: "Kyoto → Nara → Kyoto", titulo: "Bate-volta a Nara + Nishiki Market", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (9h–12h)", desc: "Trem para Nara (~45 min). Parque de Nara: 1.200 veados sagrados + biscoitos shika senbei." },
      { t: "Tarde (12h–16h)", desc: "Todai-ji (Grande Buda de bronze, 15m) e Kasuga Taisha (santuário das mil lanternas). Prove o mochi do Nakatanidou." },
      { t: "Noite (17h–21h)", desc: "Retorno a Kyoto. Jantar e compras gastronômicas no Nishiki Market ('a cozinha de Kyoto')." },
    ],
    transporte: "JR Nara Line ou Kintetsu (Kyoto ⇄ Nara, ~45 min)",
    obs: "Meio dia inteiro (5–6h) é suficiente para os destaques de Nara.",
    places: ["kintetsu-nara", "narapark", "todaiji", "kasuga", "nakatanidou", "nishiki"] },
  { d: 11, date: "2026-08-03", dow: "seg", cidade: "Kyoto → Hiroshima", titulo: "Hiroshima e Parque Memorial da Paz", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã", desc: "Check-out em Kyoto (até 10h). Shinkansen Sanyo Kyoto → Hiroshima (~1h40, Nozomi/Sakura). Deixe as malas no hotel (fica coladinho no Peace Park)." },
      { t: "Tarde (13h–17h)", desc: "Parque Memorial da Paz + Museu (~2–3h) — com o icônico Genbaku Dome, a ~10 min a pé do hotel. Jantar: okonomiyaki estilo Hiroshima no Okonomimura." },
      { t: "Noite", desc: "OPCIONAL: bonde/JR até Miyajimaguchi + ferry para ver o torii iluminado ao entardecer (e volte a dormir em Hiroshima). OU noite tranquila na Hondori (rua comercial coberta)." },
    ],
    transporte: "Shinkansen Sanyo (Kyoto → Hiroshima) + bonde Hiroden até Tōkaichi-machi (hotel/Peace Park)",
    obs: "MUDANÇA: você dorme em Hiroshima (não em Miyajima). Miyajima passou para a manhã do dia 12. O hotel fica a 10 min a pé do Peace Park.",
    places: ["hiroshima-sta", "peacepark", "peacemuseum", "okonomimura", "hiroshimacastle", "hotel-hiroshima"] },
  { d: 12, date: "2026-08-04", dow: "ter", cidade: "Hiroshima → Miyajima → Osaka", titulo: "Miyajima de manhã e chegada em Osaka", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (8h–13h)", desc: "Saia cedo e guarde a mala nos coin lockers da Hiroshima Station. Trem JR até Miyajimaguchi (~27 min) + ferry (~10 min). Itsukushima e o torii (veja a tábua de marés — maré baixa dá para caminhar até ele), ropeway ao Monte Misen, momiji manju e anago-meshi no almoço." },
      { t: "Tarde", desc: "Ferry de volta + trem a Hiroshima, pegue a mala + Shinkansen Sanyo até Shin-Osaka (~1h20–1h40). Metrô Midosuji até o hotel (check-in a partir das 16h)." },
      { t: "Noite", desc: "Dotonbori à noite (a ~5 min a pé do hotel): Glico Man, caranguejo da Kani Doraku, takoyaki no Wanaka." },
    ],
    transporte: "JR Sanyo (Hiroshima ⇄ Miyajimaguchi) + Ferry + Shinkansen Sanyo até Shin-Osaka + Metrô Midosuji até Namba/Shinsaibashi",
    obs: "Dia puxado e sem o torii iluminado (isso exigia dormir na ilha), mas você vê Miyajima inteira de dia. Confira a tábua de marés e a última balsa. Checkout é 10h — dá para sair antes e deixar a mala no locker.",
    places: ["miyajimaguchi", "itsukushima", "misen", "miyajima-omotesando", "anagomeshi", "hiroshima-sta", "shinosaka", "dotonbori", "wanaka", "kanidoraku", "hotel-osaka"] },
  { d: 13, date: "2026-08-05", dow: "qua", cidade: "Osaka", titulo: "Universal Studios Japan — dia inteiro", prioridade: "Imperdível",
    periodos: [
      { t: "Dia inteiro", desc: "Chegue 30–45 min ANTES da abertura. Super Nintendo World primeiro (Mario Kart, Mine Cart Madness, Donkey Kong Country — use Area Timed Entry pelo app se não tiver Express Pass). Depois Harry Potter, Jurassic Park, Minion Park, Hollywood Dream." },
      { t: "Noite", desc: "Atrações noturnas + compras finais na CityWalk." },
    ],
    transporte: "Do hotel (Namba/Shinsaibashi): Metrô Midosuji até Umeda → a pé até Osaka Station → JR Osaka Loop Line até Nishikujo → JR Yumesaki (Sakurajima) Line até Universal City (~40–45 min no total)",
    obs: "2026 = 25º aniversário, público recorde. Studio Pass (3 meses antes) + Express Pass praticamente essencial (filas de 2–4h sem ele). Saia do hotel bem cedo para chegar 30–45 min antes da abertura.",
    places: ["usj", "universalcity"] },
  { d: 14, date: "2026-08-06", dow: "qui", cidade: "Osaka", titulo: "Castelo, Shinsaibashi e Dotonbori", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã (9h–12h)", desc: "Castelo de Osaka: exterior e jardins gratuitos e fotogênicos; museu opcional (~1h)." },
      { t: "Tarde (13h–18h)", desc: "Shinsaibashi-suji (moda, streetwear, Don Quijote gigante) e Den Den Town (eletrônicos, games, anime — Mandarake e Animate)." },
      { t: "Noite (18h–22h)", desc: "Dotonbori e Namba: kushikatsu no Daruma (não repita o molho!), ponte Ebisubashi (foto com o Glico) e vielas de Hozenji Yokocho." },
    ],
    transporte: "Metrô Osaka — linhas Midosuji/Chuo",
    obs: "Melhor dia para eletrônicos em Den Den Town. Extra: Pokémon Center Osaka fica em Umeda (Daimaru).",
    places: ["osakacastle", "shinsaibashi", "dendentown", "dotonbori", "daruma", "kanidoraku", "hozenji", "mizuno", "pokemon-osaka", "shinsekai", "nambayasaka", "harukas", "glion"] },
  { d: 15, date: "2026-08-07", dow: "sex", cidade: "Osaka → Tóquio", titulo: "Kuromon Ichiba e retorno a Tóquio", prioridade: "Transição (leve)", leve: true,
    periodos: [
      { t: "Manhã (9h–12h)", desc: "Kuromon Ichiba Market: wagyu na hora, frutos do mar e frutas premium. Alternativa: compras finais em Shinsaibashi ou Umeda." },
      { t: "Tarde", desc: "Shinkansen Shin-Osaka → Tóquio (~2h30, Nozomi) — o trecho mais longo do roteiro." },
      { t: "Noite", desc: "Check-in em Tóquio. Últimas compras na Character Street da Tokyo Station (Ghibli, Pokémon, Hello Kitty) e jantar de despedida." },
      { t: "Madrugada (opcional, 22h–2h)", desc: "Última chance do Daikoku PA: SEXTA À NOITE, encontro de carros em Yokohama via tour guiado (busca no hotel). Grande final da viagem — mas só se o voo do dia 16 NÃO for de manhã cedo." },
    ],
    transporte: "Shinkansen Tokaido — Shin-Osaka → Tóquio",
    obs: "Dia de descompressão. Se o voo for cedo, considere hotel perto do aeroporto e faça o Daikoku na sexta do dia 1 (24/07) em vez desta.",
    places: ["kuromon", "umeda", "shinosaka", "tokyostation", "rokurinsha", "daikoku", "hotel-tokyo"] },
  { d: 16, date: "2026-08-08", dow: "sáb", cidade: "Tóquio", titulo: "Compras finais e voo de retorno", prioridade: "Imperdível",
    periodos: [
      { t: "Manhã", desc: "Compras de última hora (Pokémon Center ou Sanrio se ainda não foi) ou fechar as malas com calma." },
      { t: "Tarde", desc: "Traslado ao aeroporto: Narita Express/Skyliner/Limousine Bus (Narita) ou Monorail/Keikyu (Haneda)." },
      { t: "Noite", desc: "Voo internacional de retorno. Boa viagem! 🎌" },
    ],
    transporte: "Narita Express / Skyliner / Limousine Bus ou Monorail/Keikyu",
    obs: "Chegue ao aeroporto com 3h de antecedência; confirme o terminal com a companhia. Seu hotel (Sugamo) está reservado até 09/08 (dom) — se o voo for no dia 9, você ganha a manhã extra; se for hoje (08/08), o check-out é às 11h.",
    places: ["tokyostation", "narita", "haneda"] },
];

// ================= INFORMAÇÕES POR CIDADE =================
const CITY_INFO = {
  "Tóquio": {
    transporte: "Metrô Tokyo Metro + Toei Subway. A linha JR Yamanote (circular) é a espinha dorsal e conecta os principais bairros. Use Suica para tudo.",
    bairros: "Asakusa (tradicional), Akihabara (otaku), Shibuya/Harajuku (jovem), Shinjuku (neon e compras), Ginza (luxo), Odaiba (futurista), Ikebukuro (anime/Pokémon).",
    dicas: ["Suica na Apple Wallet resolve trem, metrô, ônibus e konbini.", "Lojas tax-free acima de ¥5.000 — ande com o passaporte.", "Konbini (7-Eleven, Lawson, FamilyMart) = comida boa e barata 24h."],
  },
  "Kyoto": {
    transporte: "Predominantemente ônibus municipal (Kyoto City Bus) — considere o passe diário. JR Nara Line para Fushimi Inari e Nara; trem/ônibus para Arashiyama.",
    bairros: "Higashiyama (templos e ruelas históricas), Gion (gueixas), Arashiyama (bambu e rio), região da Station (compras e ramen).",
    dicas: ["Templos famosos: quanto mais cedo, melhor (7h–8h).", "Ônibus lotam — o trem JR para Fushimi/Arashiyama costuma ser mais rápido.", "Reserve kaiseki com 1–4 semanas de antecedência."],
  },
  "Nara": {
    transporte: "De Kyoto: JR Nara Line (~45 min) ou Kintetsu (mais central). Tudo caminhável a partir da estação (~15–20 min até o parque).",
    bairros: "Nara Park (veados e templos), Naramachi (casas tradicionais).",
    dicas: ["Esconda mapas e papéis — os veados comem!", "Faça uma reverência ao veado e ele reverencia de volta.", "Meio dia é suficiente para os destaques."],
  },
  "Hiroshima": {
    transporte: "Bonde (streetcar) da estação ao Peace Park (~15 min) ou a pé pelo centro. JR Sanyo Line até Miyajimaguchi (~30 min).",
    bairros: "Centro/Peace Park, Hondori (rua comercial coberta), Shintenchi (Okonomimura).",
    dicas: ["Reserve 2–3h para o museu + parque.", "Okonomiyaki de Hiroshima leva lámen na massa — prove no Okonomimura.", "Você dorme aqui na noite de 03/08 (hotel colado no Peace Park). Miyajima é bate-volta na manhã do dia 12 — deixe a mala nos coin lockers da Hiroshima Station."],
  },
  "Miyajima": {
    transporte: "Ferry JR ou Matsudai de Miyajimaguchi (~10 min). Na ilha, tudo a pé + ropeway ao Monte Misen.",
    bairros: "Área do santuário e rua Omotesando (comércio).",
    dicas: ["Veja a tábua de marés: maré alta = torii flutuando; baixa = caminhe até ele.", "Veados aqui também! Não alimente com comida humana.", "Bate-volta pela manhã (dia 12) partindo de Hiroshima — chegue cedo, antes das excursões, e reserve tempo para o ropeway do Monte Misen."],
  },
  "Osaka": {
    transporte: "Metrô Osaka Metro — linha Midosuji liga Umeda a Namba/Shinsaibashi. JR Loop Line para a Universal Studios.",
    bairros: "Namba/Dotonbori (neon e comida), Shinsaibashi (compras), Den Den Town (eletrônicos/anime), Umeda (shoppings), Shinsekai (retrô).",
    dicas: ["Osaka é a capital gastronômica: takoyaki, okonomiyaki, kushikatsu.", "Kushikatsu: NUNCA molhe o espetinho 2x no molho comum.", "Express Pass da USJ esgota — compre junto com o Studio Pass."],
  },
};

// ================= EXTRAS =================
const CHECKLIST = [
  { g: "Reservas essenciais", itens: [
    "Passagens aéreas internacionais",
    "Ingresso Tokyo DisneySea (janela abre 2 meses antes, 14h JST)",
    "Studio Pass + Express Pass da Universal (3 meses antes)",
    "Hospedagem: Kyoto (Rest Collection Gion-Shijo), Hiroshima (Naka-ku), Osaka (BLUE Shimanouchi) ✓ + Tóquio",
    "Shinkansen com assento reservado (SmartEX, até 1 mês antes)",
    "Sanrio Puroland — ingresso datado com horário (dia 1, 24/07)",
    "Restaurantes especiais (kaiseki, Pokémon Café)",
    "Tour Daikoku PA — encontro de carros (sexta 24/07 OU 07/08, à noite)",
    "eSIM (Ubigi/Airalo) ou Pocket WiFi",
    "Seguro viagem",
  ]},
  { g: "Documentos", itens: [
    "Passaporte (validade 6+ meses)",
    "Visto Japão (brasileiros: isento até 90 dias — confirmar regras vigentes)",
    "Cópias digitais dos documentos",
    "Cartão de crédito internacional avisado ao banco",
    "Ienes em espécie (muitos lugares só aceitam dinheiro)",
  ]},
  { g: "Apps para instalar", itens: [
    "Suica na Apple Wallet (antes de embarcar!)",
    "SmartEX (Shinkansen)",
    "Tokyo Disney Resort app",
    "Universal Studios Japan app",
    "Google Maps (impecável para trens no Japão)",
    "Google Tradutor (com modo câmera + japonês offline)",
    "Japan Travel by NAVITIME",
  ]},
  { g: "Mala", itens: [
    "Tênis MUITO confortável (20k+ passos/dia)",
    "Roupas leves (verão: 30–37°C, úmido)",
    "Capa de chuva compacta (temporada de chuvas/tufões)",
    "Adaptador de tomada tipo A (EUA, 100V)",
    "Power bank",
    "Toalhinha de mão (banheiros não têm papel-toalha)",
    "Mochila dobrável para compras",
  ]},
];

// ================= CARIMBOS (Goshuin & Eki Stamps) =================
const CARIMBOS = [
  { g: "Goshuin — templos e santuários 御朱印", icon: "🖋️",
    desc: "Carimbo caligrafado à mão, feito no local (~¥300–500, em dinheiro). Compre um goshuinchō (caderno próprio, ~¥1.500–2.500) no primeiro templo — muitos vendem capas exclusivas lindas. Horário típico: 9h–16h30. Peça com calma e respeito: 'Goshuin o onegaishimasu'.",
    itens: [
      { n: "Senso-ji", cidade: "Tóquio", dia: 2, dica: "No salão Yogodō, à esquerda do salão principal (~¥500). Ótimo lugar para comprar o goshuinchō." },
      { n: "Meiji Jingu", cidade: "Tóquio", dia: 3, dica: "Guichê ao lado do salão principal (~¥500). Sugestão extra do dia 3." },
      { n: "Fushimi Inari Taisha", cidade: "Kyoto", dia: 8, dica: "Escritório perto do salão principal; há outro carimbo no santuário Okusha, no meio da subida dos torii." },
      { n: "Kiyomizu-dera", cidade: "Kyoto", dia: 8, dica: "Balcão próximo à entrada do salão principal (~¥300–500)." },
      { n: "Tenryu-ji", cidade: "Kyoto", dia: 9, dica: "Na recepção do templo, junto ao jardim (~¥500). Estilo zen, mais sóbrio." },
      { n: "Kinkaku-ji (Pavilhão Dourado)", cidade: "Kyoto", dia: 9, dica: "Caligrafia famosa e concorrida — fica na saída do circuito. Sugestão extra do dia 9." },
      { n: "Todai-ji", cidade: "Nara", dia: 10, dica: "Dentro do Daibutsuden, à direita do Grande Buda (~¥300). Pode ter fila." },
      { n: "Kasuga Taisha", cidade: "Nara", dia: 10, dica: "Guichê na área central do santuário (~¥500)." },
      { n: "Santuário Itsukushima", cidade: "Miyajima", dia: 11, dica: "No corredor de saída do santuário (~¥500) — um dos goshuin mais bonitos do roteiro." },
      { n: "Daisho-in (Miyajima)", cidade: "Miyajima", dia: 12, dica: "EXTRA: templo no sopé do Monte Misen, com vários carimbos e estátuas divertidas — vale o desvio na manhã do dia 12." },
    ]},
  { g: "Eki Stamps — estações de trem 駅スタンプ", icon: "🚉",
    desc: "Carimbos GRATUITOS de autoatendimento nas estações JR — cada um com desenho exclusivo da região. Ficam perto das catracas ou do balcão de informações; leve um caderninho. Pergunte: 'Eki sutanpu wa doko desu ka?' (Onde fica o carimbo da estação?).",
    itens: [
      { n: "Estação Tokyo", cidade: "Tóquio", dia: 4, dica: "Perto do centro de informações JR East, lado Marunouchi." },
      { n: "Estação Ueno", cidade: "Tóquio", dia: 2, dica: "Desenho com os pandas do zoológico de Ueno." },
      { n: "Estação Akihabara", cidade: "Tóquio", dia: 2, dica: "Perto das catracas Electric Town." },
      { n: "Estação Shibuya", cidade: "Tóquio", dia: 3, dica: "Desenho do Hachiko — pergunte no balcão JR." },
      { n: "Estação Shinjuku", cidade: "Tóquio", dia: 5, dica: "No balcão de informações JR (estação gigante — pergunte)." },
      { n: "Estação Maihama (Disney)", cidade: "Tóquio", dia: 4, dica: "Carimbo temático da região do Tokyo Disney Resort." },
      { n: "Estação Kyoto", cidade: "Kyoto", dia: 7, dica: "JR West — perto da saída central; desenho com pagode/estação." },
      { n: "Estação JR Nara", cidade: "Nara", dia: 10, dica: "Desenho com os veados de Nara." },
      { n: "Estação Hiroshima", cidade: "Hiroshima", dia: 11, dica: "Perto das catracas Shinkansen." },
      { n: "Estação Miyajimaguchi", cidade: "Miyajima", dia: 11, dica: "Carimbo do torii flutuante — também há carimbo no terminal do ferry." },
      { n: "Estação Shin-Osaka", cidade: "Osaka", dia: 12, dica: "Área JR West, perto das catracas centrais do Shinkansen." },
      { n: "Estação Osaka / Umeda", cidade: "Osaka", dia: 14, dica: "Balcão de informações JR West." },
      { n: "Estação Universal City", cidade: "Osaka", dia: 13, dica: "Carimbo temático da área da Universal Studios." },
    ]},
];

const FRASES = [
  { pt: "O goshuin, por favor (templos)", jp: "御朱印をお願いします", romaji: "Goshuin o onegaishimasu" },
  { pt: "Onde fica o carimbo da estação?", jp: "駅スタンプはどこですか？", romaji: "Eki sutanpu wa doko desu ka?" },
  { pt: "Olá / Boa tarde", jp: "こんにちは", romaji: "Konnichiwa" },
  { pt: "Bom dia", jp: "おはようございます", romaji: "Ohayou gozaimasu" },
  { pt: "Boa noite (saudação)", jp: "こんばんは", romaji: "Konbanwa" },
  { pt: "Obrigado(a)", jp: "ありがとうございます", romaji: "Arigatou gozaimasu" },
  { pt: "Por favor / Com licença", jp: "すみません", romaji: "Sumimasen" },
  { pt: "Desculpe", jp: "ごめんなさい", romaji: "Gomen nasai" },
  { pt: "Sim / Não", jp: "はい / いいえ", romaji: "Hai / Iie" },
  { pt: "Quanto custa?", jp: "いくらですか？", romaji: "Ikura desu ka?" },
  { pt: "A conta, por favor", jp: "お会計お願いします", romaji: "Okaikei onegaishimasu" },
  { pt: "Delicioso!", jp: "おいしい！", romaji: "Oishii!" },
  { pt: "Onde fica o banheiro?", jp: "トイレはどこですか？", romaji: "Toire wa doko desu ka?" },
  { pt: "Onde fica a estação?", jp: "駅はどこですか？", romaji: "Eki wa doko desu ka?" },
  { pt: "Fala inglês?", jp: "英語を話せますか？", romaji: "Eigo o hanasemasu ka?" },
  { pt: "Não entendo", jp: "わかりません", romaji: "Wakarimasen" },
  { pt: "Pode me ajudar?", jp: "手伝ってもらえますか？", romaji: "Tetsudatte moraemasu ka?" },
  { pt: "Isento de imposto? (tax-free)", jp: "免税できますか？", romaji: "Menzei dekimasu ka?" },
  { pt: "Aceita cartão?", jp: "カードで払えますか？", romaji: "Kaado de haraemasu ka?" },
  { pt: "Sem carne/peixe, por favor", jp: "肉と魚は入れないでください", romaji: "Niku to sakana wa irenaide kudasai" },
  { pt: "Água, por favor", jp: "お水をください", romaji: "Omizu o kudasai" },
  { pt: "Saúde! (brinde)", jp: "乾杯！", romaji: "Kanpai!" },
];

const EMERGENCIA = [
  { nome: "Polícia (Japão)", tel: "110", desc: "Emergências policiais" },
  { nome: "Ambulância / Bombeiros", tel: "119", desc: "Emergências médicas e incêndio" },
  { nome: "Japan Visitor Hotline (24h, inglês)", tel: "+81-50-3816-2787", desc: "JNTO — apoio ao turista 24h, inclusive em desastres" },
  { nome: "Embaixada do Brasil em Tóquio", tel: "+81-3-3404-5211", desc: "2-11-12 Kita-Aoyama, Minato-ku. Plantão consular para emergências com brasileiros" },
  { nome: "Consulado-Geral do Brasil em Nagoia", tel: "+81-52-222-1077", desc: "Atende a região de Osaka/Kansai em algumas demandas — confirme jurisdição" },
  { nome: "Perda de cartão — bloqueio", tel: "Ligue seu banco", desc: "Anote os números internacionais do seu banco antes de viajar" },
];

const LINKS = [
  { n: "Tábua de marés de Miyajima", url: "https://www.miyajima.or.jp/english/", d: "Essencial para os dias 11–12: maré alta = torii 'flutuando'; maré baixa = caminhar até ele" },
  { n: "Previsão do tempo (JMA, oficial)", url: "https://www.jma.go.jp/bosai/forecast/", d: "Agência meteorológica do Japão — verão tem calor forte e chuvas" },
  { n: "Alerta de tufões (JMA)", url: "https://www.jma.go.jp/bosai/map.html#contents=typhoon", d: "Fim de julho/agosto é temporada — cheque se aparecer aviso" },
  { n: "Status dos trens — JR East (Tóquio)", url: "https://traininfo.jreast.co.jp/train_info/e/", d: "Atrasos e interrupções em tempo real" },
  { n: "Status dos trens — JR West (Kyoto/Osaka/Hiroshima)", url: "https://trafficinfo.westjr.co.jp/en/", d: "Atrasos e interrupções em tempo real" },
  { n: "SmartEX — reservar Shinkansen", url: "https://smart-ex.jp/en/", d: "Compre os trechos de trem-bala pelo app (até 1 mês antes)" },
  { n: "Tokyo Disney Resort (DisneySea)", url: "https://www.tokyodisneyresort.jp/en/", d: "Ingresso datado — venda abre 2 meses antes, 14h JST" },
  { n: "Universal Studios Japan", url: "https://www.usj.co.jp/web/en/us", d: "Studio Pass + Express Pass — venda 3 meses antes" },
  { n: "Sanrio Puroland", url: "https://en.puroland.jp/", d: "Ingresso com horário marcado para o dia 1 (24/07)" },
  { n: "Museu Ghibli", url: "https://www.ghibli-museum.jp/en/", d: "Ingressos vendem no dia 10 do mês anterior — plano B de chuva" },
  { n: "Nintendo Museum (Uji)", url: "https://museum.nintendo.com/", d: "Sorteio de ingressos ~3 meses antes — sugestão extra de Kyoto" },
  { n: "Pokémon Café — reservas", url: "https://reserve.pokemon-cafe.jp/", d: "Reserva obrigatória, abre com semanas de antecedência" },
  { n: "Daikoku PA — tours guiados", url: "https://daikokutour.com/", d: "Encontro de carros JDM (sexta à noite, dia 1 ou 15) — acesso só de carro, reserve o tour antes" },
  { n: "Daikoku PA — tours no Viator", url: "https://www.viator.com/searchResults/all?text=Daikoku", d: "Alternativa para comparar operadores/preços do tour noturno" },
  { n: "NISMO Showroom — calendário", url: "https://www.nismo.co.jp/en/omori_factory/index_en.html", d: "Extra opcional em Yokohama (só fins de semana) — confirme os dias abertos" },
];

const ETIQUETA = [
  "Silêncio no transporte público — nada de ligações dentro do trem.",
  "Filas organizadas para tudo: trens, elevadores, restaurantes.",
  "Tire os sapatos em templos, ryokans e restaurantes tradicionais (repare no degrau/tapete).",
  "Gorjeta NÃO é costume — pode até ofender.",
  "Lixeiras públicas são raras: carregue seu lixo até o hotel/konbini.",
  "Nunca fotografe gueixas/maikos de perto — em Gion há multas.",
  "Tatuagens podem ser restritas em onsens tradicionais — verifique antes.",
  "Evite comer andando na rua — pare ou coma no local da compra.",
  "Tenha ienes em espécie: muitos lugares ainda preferem dinheiro.",
];
